### ISSUE TITLE
Using different US site location on DdSdkConfiguration causes undescriptive error

### ISSUE THREAD

**Issue by aerifiu** [DataDog/dd-sdk-flutter#117]
Creating a `DdSdkConfiguration` and setting the `site` to `DatadogSite.us1` while your account is in DatadogSite.us5. The SDK fails with this error:

`Batch 792f844c-d9ee-40eb-b2b2-ef5ef7f53bd6 [2519 bytes] (RumOkHttpUploaderV2) failed because of a processing error or invalid data; the batch was dropped.`

Changing it to us5 fixes it and setting it back to us1 reproduces the error.

**Steps to reproduce the issue:**
Create new flutter project with the wizard from android studio and add tracking to the button:
`DatadogSdk.instance.rum!.addUserAction(RumUserActionType.tap, "foo");`

**Expectation**
To work for all US sites since it is not mentioned in the docs that this setting must correspond.

**Additional context**
 - Dart/Flutter version: 2.10.5
 - Android/iOS OS version: API29
 - Device Model: emulator
 - Datadog SDK version: 1.0.0-beta.1

**Comment by fuzzybinary** [comment]
Hi @aerifiu,

Thanks for the feedback!  We actually saw this recently in the native SDKs and fixes will be landing there shortly. (https://github.com/DataDog/dd-sdk-ios/pull/845 and https://github.com/DataDog/dd-sdk-android/pull/899)

Once those new versions are released an we upgrade, that should fix the error message on the Flutter side as well.

I'll leave this open and close it when the new Native SDKs get pulled into Flutter.

**Comment by fuzzybinary** [comment]
This should now be fixed with the release of v1.0.0-beta.2
