### ISSUE TITLE
Expose DdLogs publicly

### ISSUE THREAD

**Issue by tshedor** [DataDog/dd-sdk-flutter#121]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : `datadog_flutter_plugin`
- Library type: client
- Library version: 1.0.0-beta.1

**Is your feature request related to a problem? Please describe.**

We utilize a class to store our loggers, and we cannot use the `DdLogs` type when specifying a field of the class.

**Describe the solution you'd like**

`DdLogs` is a publicly exposed class in an export.

**Describe alternatives you've considered**

Importing a `/src/` file, although this is not considered effective Dart.

**Comment by fuzzybinary** [comment]
Thanks for the feedback Tim!

This is definitely an issue, especially since DatadogSdk.createLogger returns a DdLogs object, it should likely be exposed at the top package level.
