### ISSUE TITLE
Get more informations with iOS

### ISSUE THREAD

**Issue by iTEEECH** [DataDog/dd-sdk-flutter#133]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : datadog_flutter_plugin
- Library type: monitoring
- Library version: 1.0.0-beta.1

**Is your feature request related to a problem? Please describe.**

Hi, Currently I only receive name: iPhone, model: iPhone on Datadog dashboard RUM.

**Describe the solution you'd like**
I would like to know if it was possible to further develop the information received on the RUM Dashboard of Datadog. I explain, is it possible to have in a future version the detail of the models of phones on iOS example: iPhone 8, iPhone X, etc.? 

Maybe allow to send additional information as well. I saw that there was a property defined in Configuration but impossible to access because not defined in the manufacturer.

 I haven't tested it on Android yet, maybe that's the case too. 

Thanks

**Comment by xgouchet** [comment]
Hi @iTEEECH , indeed that's a limitation that we identified and we are planning to improve the information we provide along the lines of what you're suggesting. This enhancement will come first on the [native iOS SDK](https://github.com/DataDog/dd-sdk-ios) and shortly after for the Flutter SDK.

**Comment by iTEEECH** [comment]
Hi @xgouchet, great ! thank you

**Comment by fuzzybinary** [comment]
This should be resolved with rc.3
