### ISSUE TITLE
[`datadog_tracking_http_client`] Reduce dart dependency version

### ISSUE THREAD

**Issue by danielgomezrico** [DataDog/dd-sdk-flutter#144]
**Is your feature request related to a problem? Please describe.**
When I include `datadog_tracking_http_client 1.0.1-beta.1` in my pubspec it fails because of:

```console
Because client depends on datadog_tracking_http_client >=1.0.1-beta.1 which requires SDK version >=2.17.0-0 <3.0.0, version solving failed.
pub get failed (1; Because client depends on datadog_tracking_http_client >=1.0.1-beta.1 which requires SDK version >=2.17.0-0 <3.0.0, version solving failed.)
``` 

**Describe the solution you'd like**
Reduce the min version of dart required by this package

**Additional context**
This version of dart is required for flutter 3.0 but not for flutter 2, so currently this is only usable from flutter 3

**Comment by fuzzybinary** [comment]
I've updated the README for dart_http_tracking_client to clarify the Dart 2.16 / Flutter 2.10 support:  https://github.com/DataDog/dd-sdk-flutter/tree/develop/packages/datadog_tracking_http_client#flutter-210-support

Long term, the 1.0.x line will continue to support Dart 2.16 and 1.1.0 will be Dart 2.17
