### ISSUE TITLE
Ability to start a new RUM session within a kiosk app

### ISSUE THREAD

**Issue by scopendo** [DataDog/dd-sdk-flutter#147]
When developing kiosk apps, where a single device is used, often anonymously, by many people over time, it would be useful to be able to manually force the start of a new RUM session, even though the app itself is not restarting.

**Comment by fuzzybinary** [comment]
This is currently a limitation on the native side I believe, but potentially solvable soon with some native changes that are in the pipe.

**Comment by fuzzybinary** [comment]
This is now available in 1.4.0
