### ISSUE TITLE
Could not find module 'Datadog' for target 'arm64-apple-ios-simulator'

### ISSUE THREAD

**Issue by FBisca** [DataDog/dd-sdk-flutter#154]
**Describe what happened**
Our company is implementing Datadog and we decided to try out the Flutter plug-in but it seems that it doesn't support compilation for iOS Simulators.

```shell
Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Swift Compiler Error (Xcode): Could not find module 'Datadog' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, at: $PROJET_ROOT/build/ios/Debug-dev-iphonesimulator/DatadogSDK/Datadog.framework/Modules/Datadog.swiftmodule
/private/var/lib/flutter/.pub-cache/hosted/pub.dartlang.org/datadog_flutter_plugin-1.0.0-beta.2/ios/Classes/DatadogFlutterModels.swift:5:7

Could not build the application for the simulator.
```
Since it's an installed Flutter plugin I don't think there's an easy way to control if it should be included or not if the target is a Simulator, making it impossible to run the project on an iOS Simulator.

**Steps to reproduce the issue:**
- Add `datadog_flutter_plugin: 1.0.0-beta.2` to your `pubspec.yaml`
- Run `flutter pub get` and `pod install`
- Try to execute the project targeting any iOS Simulator

**Describe what you expected:**
Project be compiled without any error.

**Additional context**
 - Dart/Flutter version: **Dart 2.17.1, Flutter 3.0.1**
 - Android/iOS OS version: **iOS 15**
 - Device Model: **iPhone 13 Simulator**
 - Datadog SDK version: **1.0.1-beta.2**
 - Versions of any other relevant dependencies: **datadog_tracking_http_client: 1.0.1-beta.1**

**Comment by fuzzybinary** [comment]
Hi @FBisca,

Thanks for reaching out. I'm guessing you're building on an M1 Mac?  I find it odd that XCode built the x64 version of the Datadog module, but maybe there's something wrong in one of our Podspecs.

Can you do me a favor and try a clean rebuild, either through XCode or using `flutter clean`, and see if the problem persists?

Thanks!

**Comment by fuzzybinary** [comment]
Thank for the additional info. We're looking into it.

Do you have any other Flutter plugins with a native component that do not have this issue? IF so, which one?

**Comment by FBisca** [comment]
At the moment I think just `firebase_crashlytics` https://pub.dev/packages/firebase_crashlytics

**Comment by fuzzybinary** [comment]
Hi @FBisca and @brunosp15 ,

I have some limited access to an M1 mac, but I wasn't able to reproduce this in the simple cases with Flutter 3.0.3 and XCode 13.4.1. I used brew, Cocoapods, and swiftlint all installed to a non-rosetta terminal. 

The two cases I tried:

First, clone this repo, and go into `packages/datadog_flutter_plugin/example` and run `flutter run`. This ran on the simulator properly.

Second, I created a new project with `flutter create --platforms ios test`, ran `pod install` from the `ios` directory, then `flutter run` from the root. This also ran correctly on the simulator.

There are two things I can think to check which might have been holdovers if these are old Flutter projects.  First, check that the Architectures property in the build settings for Runner and the Pod are both set to `$(ARCHS_STANDARD)`, and that the only excluded architecture is i386
<img width="951" alt="image" src="https://user-images.githubusercontent.com/249982/176516927-29b97777-881b-43e9-9a78-b9191fc4b3f6.png">

If everything looks okay, can one of you run the second case (new project, only add the Datadog plugin) and see if it works? If so, we'll need to keep looking in your projects setups for possible misconfiguration.

**Comment by FBisca** [comment]
Sorry that I took that long to reply, I tried to create a new project and it seems to be working fine, also the example.

I checked the `${ARCHS_STANDARD}` in your project and it's already properly set.

I'll investigate it a little more, compare our project `project.pbxproj`. I'll keep you posted, thanks for the help.

**Comment by fuzzybinary** [comment]
Please keep me posted @FBisca. I'd love to know how to resolve this in case it happens to others.

Thanks!

**Comment by fuzzybinary** [comment]
Thanks for the explanation! Closing for now.

@brunosp15 can you see if you have a similar issue?  We can reopen if you find something we need to adjust.

Thanks all!

**Comment by dustin-graham** [comment]
@fuzzybinary Please re-open this issue. We just discovered that we have this same problem. We just moved from the community plugin to this one and now we cannot run any of our flutter apps on simulator that have this DataDog dependency. I did as you instructed above and verified our excluded architectures are as you showed. Please advise. It's important to our team that Simulators are available.
