### ISSUE TITLE
Datadog deobfuscation for logs 

### ISSUE THREAD

**Issue by Doetheman** [DataDog/dd-sdk-flutter#156]
My team is planning to obfuscate our flutter application but read in this [thread](https://github.com/DataDog/dd-sdk-android/issues/372#issuecomment-836627037) that this is not possible? If not, could we add this to the feature roadmap.

**Comment by fuzzybinary** [comment]
Hi @Doetheman,

Deobfuscation and source mapping are on the roadmap for RUM Errors at the moment, but I can't give you a timeline on it yet.

However, I don't know of any plans to deobfuscate stack traces in logs.  I'll need @xgouchet to weigh in on that.

**Comment by xgouchet** [comment]
Deobfuscation of stacktrace for now is only performed for errors and crashes reported through RUM. We might do it for logs too eventually, but it's not on our immediate roadmap.

**Comment by fuzzybinary** [comment]
Deobfuscation of stack traces sent in Logs is now in for Flutter. You will need to send the stack trace as the 'stackTrace' parameter in the various log functions, which is new to 1.2.0
