### ISSUE TITLE
RUM events sometimes missing in Datadog

### ISSUE THREAD

**Issue by scopendo** [DataDog/dd-sdk-flutter#189]
It would be useful to be able to force more frequent flushes of data to Datadog.  It's not clear to me what actions I can take to trigger the upload, as sometimes when running locally it seems like it can take a long time for actions to appear in Datadog – if at all.

I have the upload frequency set to `UploadFrequency.frequent` in `DdSdkConfiguration`.

**Comment by scopendo** [comment]
I've just noticed [this](https://github.com/DataDog/dd-sdk-flutter/pull/187/files#diff-49a0f2c41ec68dedb9d4620cc6e3282c89af608f15dc0ae5bfcc01daa676e6f9R195) and set the SDK verbosity to verbose.

It seems that the SDK is pumping data to Datadog frequently just that sometimes it isn't showing up in Datadog – at other times it will, without any change in the app itself – so possibly an issue on the DD backend.

**Comment by scopendo** [comment]
Actually, rather than a backend error, I wonder if the problem is to do with hot restarts or reloads, as I have noticed this message on occasion:

> flutter: [DATADOG SDK] 🐶 → 13:57:22.580 [WARN] The `Global.rum` was called but no `RUMMonitor` is registered. Configure and register the RUM Monitor globally before invoking the feature:
    Global.rum = RUMMonitor.initialize()
See https://docs.datadoghq.com/real_user_monitoring/ios

**Comment by fuzzybinary** [comment]
Hi @scopendo -- can you post your configuration code and any messages you get during initialization?

I'm surprised you can end up in a situation where you have a `Datadog.instance.rum` but the RUMMontior isn't registered.

It is possible this is related to hot restart. Currently, modifying the configuration of the Datadog SDK and hot reloading / hot restarting is not supported, but shouldn't break, it should just ignore the new configuration until you do a full restart. The next version should warn you about this but beta.3 probably won't.

Can you give me any more info on how to replicate?

**Comment by omartinma** [comment]
Not sure if related but when I use hot restart i get this message as well
```
flutter: 🔥 Datadog SDK usage error: SDK is already initialized.
flutter: 🔥 Datadog SDK usage error: The `RUMMonitor` instance was already created. Use existing `Global.rum` instead of initializing the `RUMMonitor` another time.
```

**Comment by fuzzybinary** [comment]
@omartinma That warning should be fixed in the next release. See #141. Note - changing your configuration and hot reloading is still not supported, but the new version won't issue the warning if your configuration hasn't changed.

**Comment by omartinma** [comment]
Great, thanks for the info!

About missing events. Do we have a way to guarantee which events are triggered? I have certain situations in the app where calling on the same way to log my event, some of them are not registered in the console. Not sure if related but most of the cases it is when I trigger an event and right after i do a navigation.

**Comment by fuzzybinary** [comment]
@omartinma Can you open a separate issue for that? Provide info on your setup, including if you're using DatadogNavigationObserver or the RouteAwareMixin, and in what method you're triggering the event.

Thanks!

**Comment by omartinma** [comment]
@fuzzybinary i did some tests and all my events missed are coming when I open a BottomSheet, not sure if an issue or I am missing anything, should i create the issue just in case?

**Comment by omartinma** [comment]
Actually the problem was that bottom sheet was missing route name! Thanks anyway :D

**Comment by scopendo** [comment]
> Hi @scopendo -- can you post your configuration code and any messages you get during initialization?
> 
> I'm surprised you can end up in a situation where you have a `Datadog.instance.rum` but the RUMMontior isn't registered.
> 
> It is possible this is related to hot restart. Currently, modifying the configuration of the Datadog SDK and hot reloading / hot restarting is not supported, but shouldn't break, it should just ignore the new configuration until you do a full restart. The next version should warn you about this but beta.3 probably won't.
> 
> Can you give me any more info on how to replicate?

Hi @fuzzybinary – here's the code that I use for initialization at the moment, which is called once by our custom "runner" approach when the app starts up, before calling Flutter's `runZonedGuarded`.

```dart
  const rumApplicationId = String.fromEnvironment(
    'DATADOG_RUM_APPLICATION_ID',
    defaultValue: '...',
  );

  final configuration = DdSdkConfiguration(
    clientToken: clientToken,
    env: flavor,
    site: DatadogSite.eu1,
    firstPartyHosts: ['example.com'],
    trackingConsent: TrackingConsent.granted,
    uploadFrequency: UploadFrequency.frequent,
    batchSize: BatchSize.small,
    nativeCrashReportEnabled: true,
    loggingConfiguration: LoggingConfiguration(),
    rumConfiguration: rumApplicationId.isEmpty
        ? null
        : RumConfiguration(applicationId: rumApplicationId),
  );

  configuration.enableHttpTracking();
  DatadogSdk.instance.sdkVerbosity = Verbosity.info;
  DatadogSdk.instance.initialize(configuration);
```

**Comment by scopendo** [comment]
Here's the output showing DD console logging when the app first starts.  My initialisation code runs whenever you see the "Initializing Datadog..." message.  You can see our own console logging indicating API calls, which will DD should also be logging due to HTTP tracking, as well as an info log message that we output using DD.

```
flutter: Initializing Datadog integration for RUM and remote logging
flutter: GET /user/session/check
flutter: GET /visitor/locations?manage=true
flutter: GET /user/current
flutter: [INFO]: App restarting with existing credentials
flutter: [DATADOG SDK] 🐶 → 08:40:21.765 [WARN] Tracing feature is enabled, but no `Tracer` is registered. The Tracing integration with Logging will not work.
flutter: GET /org/2830
flutter: [DATADOG SDK] 🐶 → 08:40:28.626 [INFO] NTP time synchronization completed.
Server time will be used for signing events (0.049s difference with device time).
```

And here's the output after doing nothing except for a hot **restart**.

```
Performing hot restart...
Syncing files to device iPad (9th generation)...
Restarted application in 641ms.
flutter: Initializing Datadog integration for RUM and remote logging
flutter: 🔥 Datadog SDK usage error: SDK is already initialized.
flutter: 🔥 Datadog SDK usage error: The `RUMMonitor` instance was already created. Use existing `Global.rum` instead of initializing the `RUMMonitor` another time.
flutter: [DATADOG SDK] 🐶 → 08:47:50.971 [WARN] The `Global.rum` was called but no `RUMMonitor` is registered. Configure and register the RUM Monitor globally before invoking the feature:
    Global.rum = RUMMonitor.initialize()
See https://docs.datadoghq.com/real_user_monitoring/ios
flutter: GET /user/session/check
flutter: GET /visitor/locations?manage=true
flutter: GET /user/current
flutter: [INFO]: App restarting with existing credentials
flutter: [DATADOG SDK] 🐶 → 08:47:53.167 [WARN] RUM feature is enabled, but no `RUMMonitor` is registered. The RUM integration with Logging will not work.
flutter: [DATADOG SDK] 🐶 → 08:47:53.167 [WARN] Tracing feature is enabled, but no `Tracer` is registered. The Tracing integration with Logging will not work.
flutter: [DATADOG SDK] 🐶 → 08:47:53.185 [WARN] The `Global.rum` was called but no `RUMMonitor` is registered. Configure and register the RUM Monitor globally before invoking the feature:
    Global.rum = RUMMonitor.initialize()
See https://docs.datadoghq.com/real_user_monitoring/ios
flutter: GET /org/2830
```

**Comment by scopendo** [comment]
@fuzzybinary – I think this might be fixed with 1.0.0-rc.1.

I tried unsuccessfully to reproduce the problem with the example app (for which I needed to delete and recreate the ios folder).  I compared the `pubspec.lock` files and noticed the new release candidate.  I tried that in my app and it seems to be OK now.

**Comment by fuzzybinary** [comment]
👍  Sounds good -- it's very possible we were causing issues attempting to reinitialize during hot reload. RC1 no longer attempts to reinitialize.

I'll leave this open for a bit in case you see the error again.

Thanks for your help!

**Comment by scopendo** [comment]
Not seeing the error anymore – I'm happy for this issue to be closed when you are.
