### ISSUE TITLE
Wrong view name on navigation for user action

### ISSUE THREAD

**Issue by omartinma** [DataDog/dd-sdk-flutter#196]
**Describe what happened**
When registering a user action and immediately opening a new route the event is logged for the new route instead of the one that triggered the action.

**Steps to reproduce the issue:**

1. Open route A
2. Call addUserAction and navigates to route B.
3. Route B is opened.
4. In the console the event is registered on Route B

**Describe what you expected:**

The event should be registered on route A

**Additional context**
 - Dart/Flutter version: 3.0.1
 - Android/iOS OS version: any
 - Device Model: any
 - Datadog SDK version:  1.0.0-beta.3
 - Versions of any other relevant dependencies:

**Comment by omartinma** [comment]
Additional info:
I did some research and it just happens when using an additional state management solution(bloc in my case but I think is the same for any other using Streams). I guess as addUserAction is not async anymore compared with the previous package it is creating this issue

**Comment by omartinma** [comment]
Ok, I will try my best to create a small example later this/next week.

For simplicity, I moved the addUserAction from the bloc but it would be nice to understand why that is happening in that way. Thanks a lot!

**Comment by fuzzybinary** [comment]
Datadog _should_ always process calls in the order we receive them. If you're pushing the state change to an async handler in bloc, then triggering a navigation in Flutter, the navigation is likely handled synchronously, while the bloc request is pushed to the back of the task queue.

So, from Datadog's perspective, a new view is active when `addUserAction` is called.

But, please let me know if you're seeing any weird behavior where Datadog is being called in the correct order, but being assigned to the wrong view.

**Comment by fuzzybinary** [comment]
Hi @omartinma I'm going to close this from inactivity, but please re-open if you're still seeing this issue.
