### ISSUE TITLE
Question: Correct way to record outcome for analysis

### ISSUE THREAD

**Issue by scopendo** [DataDog/dd-sdk-flutter#198]
Sometimes we want to record outcomes to Datadog in our app to help inform future design choices.  For example, we have a search capability and we'd like to know how often users find no match, a single match or multiple matches.

What is the recommended way to record such outcomes?  At the moment we are using a custom action as that seems to report on than logging.

**Comment by fuzzybinary** [comment]
Hi @scopendo 

There are a few ways to do this. One way is just by sending a log with the attributes set for individual results, for example:
```dart
DatadogSdk.instance.logs?.info('Search completed', { 'result_count': count });
```

You could also use Custom Actions with attributes as well, for example: 
```dart
DaradogSdk.instance.rum?.addUserAction(RumUserActionType.custom, 'search completed', { 'result_count': count });
```

You may want to talk with your CSM about the particulars of you app and what you're trying to do, and they can walk you through not only what to collect but how to properly make a dashboard to track it.

Let me know if that works for you!
