### ISSUE TITLE
Document endpoints

### ISSUE THREAD

**Issue by scopendo** [DataDog/dd-sdk-flutter#201]
It would be useful for the package documentation to be updated to include the Datadog ports and endpoints that an app will send requests to.

This is particularly useful for Flutter apps that will be run on a locked-down enterprise network, where endpoints are explicitly added to an allow list.

**Comment by fuzzybinary** [comment]
@alai97 This would be useful for all Datadog SDKs -- is there already official documentation on this?

**Comment by alai97** [comment]
I don't see any available information right now, I opened DOCS-3997 to track this doc request for all Datadog SDKs!

**Comment by fuzzybinary** [comment]
@scopendo We're going to add these to the [datadog docs site](https://docs.datadoghq.com/real_user_monitoring/) in the near future, but for now, all Datadog traffic is transmitted over standard SSL (443) to the following domains, based on your "site" parameter and the feature:

- Logs 
  - us1 - https://logs.browser-intake-datadoghq.com
  - us3 - https://logs.browser-intake-us3-datadoghq.com
  - us5 - https://logs.browser-intake-us5-datadoghq.com
  - eu1 - https://mobile-http-intake.logs.datadoghq.eu
- Traces (N/A for Flutter at the moment but for reference)
   - us1 -  https://trace.browser-intake-datadoghq.com
   - us3 - https://trace.browser-intake-us3-datadoghq.com
   - us5 - https://trace.browser-intake-us3-datadoghq.com
   - eu1 - https:/public-trace-http-intake.logs.datadoghq.eu
- RUM
  - us1 - https://rum.browser-intake-datadoghq.com
  - us3 - https://rum.browser-intake-us3-datadoghq.com
  - us5 - https://rum.browser-intake-us5-datadoghq.com
  - eu1 - https://rum-http-intake.logs.datadoghq.eu

Note these may also be slightly different for Flutter Web which utilizes the Browser SDK.

**Comment by scopendo** [comment]
That's super helpful – thank you Jeff.

**Comment by fuzzybinary** [comment]
If anyone is looking for this in the future, it is now on the Datadog documentation site at https://docs.datadoghq.com/getting_started/site/
