### ISSUE TITLE
WidgetBinding analyzer noise for Flutter >=3 

### ISSUE THREAD

**Issue by charafau** [DataDog/dd-sdk-flutter#203]
Change introduced in this commit: 
https://github.com/DataDog/dd-sdk-flutter/commit/a6a66306011d20566c258d39203659feca871546

results in noisy analyzer when running from CLI:

```
./../../../.pub-cache/hosted/pub.dartlang.org/datadog_flutter_plugin-1.0.0-rc.2/lib/src/rum/rum_long_task_observer.dart:44:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Utils/flutterSdk/flutterStable/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
```

This makes tests output hard to read.

**Comment by fuzzybinary** [comment]
Hi @charafau 

Yes, I'm with you, I hate it, but fixing this will break Flutter < 3 and I'm not sure anyone has found a good workaround other than us maintaining two versions of the library (which is what we're doing with datadog_tracking_http_client). 

See https://github.com/dart-lang/sdk/issues/33249 for more on this.

Sorry 😒

**Comment by fuzzybinary** [comment]
Neverymind @charafau. Someone pointed me to a fix. We'll have it in the next version.

**Comment by charafau** [comment]
That's great to hear! Thank you!

**Comment by scopendo** [comment]
@fuzzybinary – should I still be seeing this with 1.0.0-rc.2?

```
../../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/datadog_flutter_plugin-1.0.0-rc.2/lib/src/rum/rum_long_task_observer.dart:44:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../../Developer/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance?.addObserver(this);
```

**Comment by scopendo** [comment]
Never mind – I incorrectly took the changelog message for rc.2 to mean it contained this fix but now see that there's a later commit yet to be released.

**Comment by fuzzybinary** [comment]
Yeup... sorry, rc3 will contain this. We should be able to get it out in the next day or so.

**Comment by fuzzybinary** [comment]
This is now live in 1.0.0-rc.3
