### ISSUE TITLE
DEBUG-level logs are not being sent to DataDog

### ISSUE THREAD

**Issue by mbtodorov** [DataDog/dd-sdk-flutter#216]
Thanks for taking the time for reporting an issue!

**Describe what happened**
`debug` log messages are not being sent through to DataDog

**Steps to reproduce the issue:**
1. Initialize SDK
2. Call the `debug` method: 
```dart
DatadogSdk.instance.logs?.debug("A debug message.")
```
3. Observe that the log is not coming through to DataDog:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/25320807/188181363-0ba5e02e-b9e6-4a6f-a531-beacd96eb30f.png">

**Describe what you expected:**
debug-level logs should be sent to datadog

**Additional context**
 - Dart/Flutter version: 2.17.6/3.0.5
 - Android/iOS OS version: 
 - Device Model: 
 - Datadog SDK version: 1.0.0-rc3
 - Versions of any other relevant dependencies:

**Comment by fuzzybinary** [comment]
Hi @mbtodorov,

I'm not able to reproduce this immediately. Is there anything else weird about your setup? Are you seeing this for both iOS and Android? Is there anything unusual about your setup / initialization?

**Comment by fuzzybinary** [comment]
Also, please check what you set in your configuration for your `LoggingConfiguration.datadogReportingThreshold`.  This defaults to `Verbosity.verbose`, but if you set it to `Verbosity.info`, by design it will not send `debug` or `verbose` logs to Datadog.

**Comment by mbtodorov** [comment]
Hello.

@fuzzybinary thanks for looking into my issue so swiftly. I thought perhaps it might be something well known or I am missing something. Let me go into more detail. Here is the setup:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // we have firebase initialisation
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform
  );

  // we have timezone initialisation
  tz.initializeTimeZones();

  // the logging bloc observer has a lot of `DatadogSdk.instance.logs?.debug` none of which are coming through
  Bloc.observer = LoggingBlocObserver();

  DatadogSdk.runApp(
    DdSdkConfiguration(
      clientToken: '<token>',
      env: '<env>',
      site: DatadogSite.us1,
      trackingConsent: TrackingConsent.pending, // updated after user is prompted with tracking consent
      nativeCrashReportEnabled: true,
      loggingConfiguration: LoggingConfiguration(
        sendNetworkInfo: true,
        printLogsToConsole: true,
      ),
      tracingConfiguration: TracingConfiguration(
        sendNetworkInfo: true,
      ),
      rumConfiguration: RumConfiguration(
        applicationId: '<rum-id>',
      ),
      firstPartyHosts: '...',
    )..enableHttpTracking(),
   () => runApp(
     MultiRepositoryProvider(
       providers: [] // a bunch of DI
       child: const App()
   ),
  );
}
```

Come to think of it, it might be the case that the logs are not coming through because `LoggingBlocObserver` is instantiated before calling `DatadogSdk.runApp` 🤔. Although not sure since it calls static methods. Will give it a try and post an update!

**Comment by xgouchet** [comment]
Hi @mbtodorov, indeed you need to make sure the global SDK is initialize before trying to instantiate a logger/send a log. If the Logger is instantiate before, it won't know what your configuration is, and will default to a no-op implementation.

**Comment by mbtodorov** [comment]
Ah, can confirm that the logs are coming through. I feel silly now, apologies for wasting your time. Feel free to close this!

**Comment by xgouchet** [comment]
That's okay, it's an easy thing to overlook. Glad to know the logs are coming properly.
