### ISSUE TITLE
Not collecting data for Android, but works on iOS

### ISSUE THREAD

**Issue by samuelcecilio** [DataDog/dd-sdk-flutter#250]
**Describe what happened**
I configured datadog rum for my application, but it's only working for iOS. I couldn't identify any errors, in the debug console there is a info that the SDK has been initialized.

**Steps to reproduce the issue:**
- follow setup instructions
- after adding the plugin, I had to add the following configuration in the `build.gradle` file:
- run app on ios and android emulator
- run app on physical device ios and android
- only ios devices appear on the dashboard

```
// android/app/build.gradle

configurations {
    all {
        exclude group: 'androidx.lifecycle', module: 'lifecycle-viewmodel-ktx'
    }
}
```

<img width="1116" alt="Captura de Tela 2022-10-10 às 09 27 49" src="https://user-images.githubusercontent.com/30150045/194866667-0503e6dd-fc63-4c24-85b4-14c2f6882397.png">

**Describe what you expected:**
- collect data for both ios and android

**Additional context**
 - Dart/Flutter version:
   - Flutter v3.3
 - Android/iOS OS version:
   - Tested on android api v30, v31 and v32
 - Device Model:
   - Android Emulator, Samsung S20FE, Motorola One
 - Datadog SDK version:
   - datadog_flutter_plugin:1.0.1
 - Versions of any other relevant dependencies:
   - firebase_crashlytics:2.8.13, firebase_crashlytics_platform_interface:3.2.19

**Comment by fuzzybinary** [comment]
Hi @samuelcecilio thanks for reaching out!

It sounds like you already set the `DatadogSdk.sdkVerbosity` to `Verbosity.verbose`, but if not can you do that and post what console messages you're seeing? Additionally, are you seeing any messages every so often saying whether or not Datadog has any information to send?

Lastly, have you started a view using `DatadogSdk.instance.rum?.startView()`, or by using named routes in conjunction with the `DatadogNavigationObserver`?

**Comment by samuelcecilio** [comment]
Hi, thanks. The `main.dart` looks like:

```dart
Future<void> main() async {
  runZonedGuarded<Future<void>>(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      await DatadogSdk.instance.initialize(
        DdSdkConfiguration(
          clientToken: remoteConfig.getString(CommonConsts.REMOTE_CONFIG_DATADOG_CLIENT_TOKEN),
          env: const String.fromEnvironment(Environment.buildEnv),
          site: DatadogSite.us1,
          trackingConsent: TrackingConsent.granted,
          nativeCrashReportEnabled: true,
          loggingConfiguration: LoggingConfiguration(
            sendNetworkInfo: true,
            printLogsToConsole: true,
          ),
          rumConfiguration: RumConfiguration(
            applicationId: remoteConfig.getString(CommonConsts.REMOTE_CONFIG_DATADOG_APP_ID),
            detectLongTasks: true,
          ),
        ),
      );

      FlutterError.onError = (FlutterErrorDetails details) {
        FlutterError.presentError(details);
        FirebaseCrashlytics.instance.recordFlutterError(details);
        DatadogSdk.instance.rum?.handleFlutterError(details);
      };

      runApp(
        BlocProvider.value(
          value: di.sl<AuthBloc>(),
          child: MyApp(),
        ),
      );
    },
    (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack);
      DatadogSdk.instance.rum?.addErrorInfo(error.toString(), RumErrorSource.source, stackTrace: stack);
    },
  );
}
```

`Verbosity.verbose` is the default, or do I need to set it manually?

With only this setting, I automatically get memory usage statistics and error reports for iOS, for Android I don't get any.

**Comment by fuzzybinary** [comment]
You need to set it manually.  Before calling `DatadogSdk.instance.initialize`, add:

```dart
DatadogSdk.sdkVerbosity = Verbosity.verbose;
```

The Datadog SDK is actually very verbose about what it's doing on this setting, so it is set to a lower level by default.

Are you calling `DatadogSdk.instance.rum?.startView` or are you using the `DatadogNavigationObserver`? And are you seeing views for individual sessions?

**Comment by samuelcecilio** [comment]
I had not implemented the `DatadogNavigationObserver`, apparently for iOS this was not a problem as everything was like `ApplicationLaunch`:
<img width="341" alt="Captura de Tela 2022-10-18 às 08 11 02" src="https://user-images.githubusercontent.com/30150045/196414143-299f3303-98b6-4836-908b-a246e89c136b.png">

BTW, verbosity looks differently for android and ios:
<img width="1428" alt="Captura de Tela 2022-10-18 às 08 01 29" src="https://user-images.githubusercontent.com/30150045/196413907-b75242e6-baa1-4435-8e3c-b48d0c95e50b.png">
android

<img width="1428" alt="Captura de Tela 2022-10-18 às 08 08 57" src="https://user-images.githubusercontent.com/30150045/196413929-0e49f0d7-6dee-4f6a-abd1-026633b02129.png">
iOS
