### ISSUE TITLE
setUserInfo should not overwrite previous usage

### ISSUE THREAD

**Issue by brunovsiqueira** [DataDog/dd-sdk-flutter#254]
Hi there. I'd like to discuss if this is the expected behavior.

**Describe what happened**
When you use "setUserInfo" method in order to set User RUM information more than once, only what you have set in the latest usage appear in RUM logs. It seems to clear all user information you have set even if you are setting only additional info.

**Steps to reproduce the issue:**
Call "setUserInfo" with only id, name and email.
Afterward, call "setUserinfo" with only "extraInfo" map.
In RUM log, you only see the extraInfo propertities you have set.

**Describe what you expected:**
In my opinion, it should compose userInfo instead of overwriting it. In RUM logs, I should see all the basic user info (id, name and email) added by the extraInfo I have set separeteley.

**Additional context**
 - Datadog SDK version: 1.0.1

**Comment by brunovsiqueira** [comment]
Hi @fuzzybinary. Thanks for your attention.

Ok, it's clear now and makes sense. I have implemented what you suggested and it works properly.

I agree with you that would be helpful having a separate method to add or change extra properties. If you want, you can close this issue or mark it with feature request.

**Comment by fuzzybinary** [comment]
`addUserExtraInfo` should how be available in 1.1.0
