### ISSUE TITLE
Unable to setup new application / send data

### ISSUE THREAD

**Issue by Raahim** [DataDog/dd-sdk-flutter#276]
**Describe what happened**
I am trying to add a new Flutter application in Datadog, and I am following this [guide](https://docs.datadoghq.com/real_user_monitoring/flutter/): 

I have created an app in Datadog , created the configuration object and initialized the Datadog RUM instance using the first method shown in the documentation. However, I am still not able to send any data to Datadog and stuck on "Verify your installation" step which waits for data to arrive. I have also tried the second method to initialize the library without any luck.

I am trying to use Navigation Observer for automatic screen tracking. 

Just a disclaimer I am still new to Flutter and Datadog, so it is possible I am missing some step.

**Steps to reproduce the issue:**
Create new application in Datadog RUM dashboard, follow the steps from the official guide to add the plugin into your Flutter app

**Describe what you expected:**
I was expecting the "verify your installation" step to complete, but it is stuck on "Waiting for data..."

**Additional context**
 - Dart/Flutter version: Dart SDK version: 2.18.4 (stable)/Flutter (Channel stable, 3.3.7)
 - Android/iOS OS version: Android, iOS
 - Device Model: Android Emulator Pixel 5 API 31, iOS Simulator 
 - Datadog SDK version: 1.0.1
 - Versions of any other relevant dependencies: N/A

**Comment by fuzzybinary** [comment]
Hi @Raahim

Can you set Datadog's SDK verbosity higher and see if it's reporting any errors? It's best to only enable this on debug builds like so:

```dart
if (kDebugMode) {
  DatadogSdk.instance.sdkVerbosity = Verboisty.verbose;
}
```

That should let you know if there's anything weird going on.

**Comment by Raahim** [comment]
> Hi @Raahim
> 
> Can you set Datadog's SDK verbosity higher and see if it's reporting any errors? It's best to only enable this on debug builds like so:
> 
> ```dart
> if (kDebugMode) {
>   DatadogSdk.instance.sdkVerbosity = Verboisty.verbose;
> }
> ```
> 
> That should let you know if there's anything weird going on.

Thanks for getting back to me.

Oddly enough, I am running into another issue now. When I add the package in the dependencies list, I run into the following problem:
`Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
lib\main.dart:1

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\rghauri\flutter\.pub-cache\hosted\pub.dartlang.org\datadog_flutter_plugin-1.1.0\android\build.gradle' line: 63

* What went wrong:
A problem occurred evaluating project ':datadog_flutter_plugin'.
> Could not get unknown property 'libs' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

This is without changing any code. Only happens when I add the dependency and run the build, without making any changes to the code. As soon as I remove this dependency, the problem goes away. 

As for setting sdkVerbosity to Verbosity.verbose, I believe I already tried it, but would like to re-try once I get pass the error I am encountering now. Do you have any ideas for the above error? Thanks!

**Comment by Raahim** [comment]
OK so downgrading to 1.0.1 from 1.1.0 fixed the building issue I was having, but changing the Verbosity didn't help with the orginal issue. I added the following line:
```dart
if (kDebugMode) {
    DatadogSdk.instance.sdkVerbosity = Verbosity.verbose;
  }
  ```
After:
```dart
await DatadogSdk.runApp(configuration, () async {
    runApp(const MyApp());
  });
```

If it helps, here is the main.dart file.
```dart
void main() async {
  final configuration = DdSdkConfiguration(
    clientToken: 'Client Token',
    env: 'dev',
    site: DatadogSite.us1,
    trackingConsent: TrackingConsent.granted,
    nativeCrashReportEnabled: true,
    loggingConfiguration: LoggingConfiguration(),
    rumConfiguration:
        RumConfiguration(applicationId: 'App ID'),
  );

  await DatadogSdk.runApp(configuration, () async {
    runApp(const MyApp());
  });

  if (kDebugMode) {
    DatadogSdk.instance.sdkVerbosity = Verbosity.verbose;
  }
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => UserProvider()),
      ],
      child: MaterialApp(
        title: 'My App',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        onGenerateRoute: RouteGenerator.generateRoute,
        navigatorObservers: [
          DatadogNavigationObserver(datadogSdk: DatadogSdk.instance),
        ],
      ),
    );
  }
}
```

**Comment by fuzzybinary** [comment]
@Raahim Thanks for pointing out the `libs` issue. I'll get a 1.1.1 out ASAP to fix that.

Add the sdkVerbosidy before calling runApp (sdkVerbosity doesn't need Datadog initialized to work, and because runApp is awaited, you're probably never reaching that code)

**Comment by Raahim** [comment]
@fuzzybinary Thanks for getting back to me. I Initilally tried to set the sdkVerbosidy before calling runApp, but it lead to this exception:
![image](https://user-images.githubusercontent.com/6942279/201115399-c2b965d1-6e7a-4945-b3f9-a63e26e6c6e6.png)

Note I removed the if condition to ensure the sdkVerbosidy is always set even though this is not a good practice, but only doing it for testing purposes.

**Comment by fuzzybinary** [comment]
😅 Sorry, let's switch over to the more manual initialization:
```dart
runZonedGuarded(() async {
      WidgetsFlutterBinding.ensureInitialized();
      DatadogSdk.instance.sdkVerbosity = Verbosity.verbose;
      await DatadogSdk.instance.initialize(configuration);

      runApp(const MyApp());
    }, (e, s) {
      DatadogSdk.instance.rum?.addErrorInfo(
        e.toString(),
        RumErrorSource.source,
        stackTrace: s,
      );
    });
```

By the way, my guess is this is a site mismatch. Does the parameter you're passing to `DdSdkConfiguration.site` match the Datadog subdomain you're using?

**Comment by Raahim** [comment]
@fuzzybinary Thanks for getting back, but unfortunately manual initialization also didn't work :(

As for the site, I have it set to:
```dart
site: DatadogSite.us1
```

And I am using app.datadoghq.com which I believe is US1, at least according to this [page](https://docs.datadoghq.com/getting_started/site/). 

I'm running out of ideas as to what to do haha. I have the client token, env, app ID all set, which I copied from the Edit RUM App Page, and it still doesn't seem to work. Is there anything else I need to be doing beside installing the package, importing it, creating the configuration object and initialization the instance? By chance, do I need to do anything else? I have also tried to send a log manually, but that didn't seem to work either.

**Comment by fuzzybinary** [comment]
One more thing @Raahim  -- 

Though this shouldn't have affected manually sending a log, the `DatadogNavigationObserver` only works with named routes, and doesn't send any data to RUM until a view is active. If you want to test and see if it's just that no views are active, try adding `DatadogSdk.intance.rum?.startView('MyView')` (or similar) in `initState` on your first screen.

**Comment by Raahim** [comment]
@fuzzybinary Thank you, it does look like corporate proxy was the problem. After switching to manual initiation and getting off the corporate proxy, it seems to work! I can see 1 view load up in the dashboard now (the default event Application_start on screen ApplicationLaunch), but the other views aren't showing up even though I am using PushNamed. I am using onGenerateRoute with a static function that looks something like this:
```dart
 static Route<dynamic> generateRoute(RouteSettings settings) {
    switch (settings.name) {
      case "/":
        return MaterialPageRoute(builder: (_) => const HomeScreen());
      case "/screen1":
        return MaterialPageRoute(builder: (_) => const ScreenOne());
      case "/screen2":
        final arg = settings.arguments as String;
        return MaterialPageRoute(
            builder: (_) => ScreenTwo(arg : arg));
      default:
        return MaterialPageRoute(builder: (_) => const ErrorScreen());
    }
  }
```

Also, is there another place to ask how-to questions? Make Discord?

**Comment by fuzzybinary** [comment]
@Raahim We pull the name out of the `RouteSettings` on the generated route. The simple fix is just to pass the `RouteSettings` into the MaterialPageRoute:
```dart
case "/screen1":
  return MaterialPageRoute(
    builder: (_) => const ScreenOne(),
    settings: settings,
  );
```

The larger fix would be to look into a routing library that is Flutter Web ready (like go_router or auto_route) which would work out of the box with the `DatadogNavigationObserver`

Datadog has a [public slack channel](https://chat.datadoghq.com/) and you can also reach out to Datadog support with any issues as well.
