### ISSUE TITLE
Building APK fails with version 1.1.0

### ISSUE THREAD

**Issue by EdwynZN** [DataDog/dd-sdk-flutter#277]
**Describe what happened**
After upgrading to `1.1.0` the Android build no longer work

**Steps to reproduce the issue:**

using datadog_flutter_plugin: ^1.1.0 in pubspec yaml creates this error after building for Android

```
Build file '/Users/runner/hostedtoolcache/Flutter/3.3.7/macos/flutter/.pub-cache/hosted/pub.dartlang.org/datadog_flutter_plugin-1.1.0/android/build.gradle' line: 63
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':datadog_flutter_plugin'.
[        ] > Could not get unknown property 'libs' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
[        ]
```
**Describe what you expected:**
Going back to a lower version fixes the problem (1.0.1) and builds the apk in debug / release

**Additional context**
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.4 21F79 darwin-arm, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.73.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

Gradle 
```
/// dependency in android/build.gradle

classpath 'com.android.tools.build:gradle:7.1.2'

/// distribution in wrapper.properties

distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-all.zip
```

**Comment by fuzzybinary** [comment]
Thanks @EdwynZN! I'm on it. I'll either have a 1.1.1 out later today or see if I can get the pub powers that be to replace 1.1.0

Thanks again!

**Comment by fuzzybinary** [comment]
v1.1.1 is now live and should fix this issue. Please let me know if you have any other problems!
