### ISSUE TITLE
Allow optional overriding of named route

### ISSUE THREAD

**Issue by christinachimi** [DataDog/dd-sdk-flutter#282]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No

**Is your feature request related to a problem? Please describe.**
My app is set up in such a way that most screens are accessed on the "home" route ("/"). Because of this, even when using `DatadogRouteAwareMixin` and overriding `RumViewInfo` I can't get any actual screen names to appear. This makes it harder to get useful data. 

**Describe the solution you'd like**
Given that I'm overriding `RumViewInfo` it seems reasonable to assume I want to see the name I'm providing. Would it be possible to allow, possibly through an additional override, this name to be used instead of the named route name?

**Describe alternatives you've considered**
I have considered re-working the app to use routes everywhere, but this is a pretty big change and would prevent us from getting use from RUM for a while. 

**Additional context**

**Comment by fuzzybinary** [comment]
Hi @christinachimi,

I'll take a look and see if I can get RouteAwareMixin and named routes to behave a bit better to satisfy this use case.

In the mean time, one potential way to solve this is to provide a [ViewInfoExtractor](https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/ViewInfoExtractor.html) to the DatadogNavigationObserver.  By default, this just checks `route.settings.name` for a route name, but if there are parameters in your route that tell you the name of the view, you can replace the name there.

**Comment by christinachimi** [comment]
@fuzzybinary thanks! that works great, at least on iOS. That actually probably solves the use case for me, so  you can close this if you don't think it has additional value.
