### ISSUE TITLE
CocoaPods referencing incorrect DatadogSDKCrashReporting version (DataDog_Flutter_Plugin 1.1.1)

### ISSUE THREAD

**Issue by adominikovic-medicallyhome** [DataDog/dd-sdk-flutter#292]
**Describe what happened**
DataDog Flutter Plugin fails build for iOS version of Flutter app. The DatadogSDK seems to be trying to use an incompatible or missing version of the DatadogSDKCrashReporting dependency (see below image). Podfile references DatadogSDKCrashReporting 1.12.0  but the Datadog Flutter Plugin is trying to use version 1.13z.0 (can't find reference to the z in version number on GitHub. Typo?). Android version of app works fine. Any assistance would be appreciated!
![image](https://user-images.githubusercontent.com/112003423/206533005-4169987b-f889-4a64-bb25-4104030a02f8.png)

**Steps to reproduce the issue:**
Try to Build iOS version of flutter app using DataDog Flutter Plugin 1.1.1 (see error stack trace below).
![Screen Shot 2022-12-08 at 10 21 13 AM](https://user-images.githubusercontent.com/112003423/206535273-f8259b4a-436e-48ac-bfb2-00b4157e32eb.png)

**Describe what you expected:**
I expected Podfile to reference DatadogSDKCrashReporting 1.13.0 since it is the latest version in this repo. 1.13z.0 may be a typo.

**Additional context**
 - Dart/Flutter version: Flutter version 3.3.9
 - Android/iOS OS version: iOS 16
 - Device Model: iPhone 14 Pro Max (simulator).
 - Datadog SDK version: 1.12.0
 - Versions of any other relevant dependencies: DataDog_Fluttter_Plugin 1.1.1

**Comment by fuzzybinary** [comment]
Hi @adominikovic-medicallyhome,

I can not reproduce with a minimal example. Here's the commands i ran:
```
flutter create --platforms ios test_app
flutter pub add datadog_flutter_plugin
flutter run
```

This builds correctly with plugin 1.1.1 and a quick inspection of `ios/Podfile.lock` shows DatadogSDKCrashReporting 1.13.0 as the installed version. Looking at the pubspec in my pubcache (`$FLUTTER_HOME/.pub-cache/hosted/pub.dartlang.org/datadog_flutter_plugin-1.1.1/ios/datadog_flutter_plugin.podspec`) also shows both DatadogSDK 1.13.0 and DatadogSDKCrashReporting 1.13.0.

My guess is something weird happened with your pubcache. I'd delete at least the datadog_flutter_plugin-1.1.1 directory and rerun `flutter pub get` on your project.

**Comment by adominikovic-medicallyhome** [comment]
Yes there did appear to be an issue with the iOS Podfile reinstalling pods seems to have fixed this issue. Closing and thank you!
