### ISSUE TITLE
Cancel an in-progress user action

### ISSUE THREAD

**Issue by christinachimi** [DataDog/dd-sdk-flutter#297]
**Is your feature request related to a problem? Please describe.**
I wanted to record taps on the `BottomNavigationBar`. This is difficult to address currently; the DD SDK does pick up on the underlying `GestureDetector` but of course the name is "unknown". I'd like to handle this by just writing my own user events when the tap occurs, but this fails if the BottomNavigationBar is under the `RumUserActionDetector`, because the SDK is already in progress on the `GestureDetector` tap event. My current solution is to not put the `BottomNavigationBar` in the `RumUserActionDetector`; but this necessitates having multiple `RumUserActionDetector` to handle detection across the app, as opposed to just wrapping the `MaterialApp`.

**Describe the solution you'd like**
Ideally the SDK would be able to pick up on BottomNavigationBar taps, but I suspect this may be difficult, since the actual tap is known about by some other stateful widget above the nav. A solution that I think could be useful would be the ability to cancel the in-progress event so that I can write my own (or, perhaps, to opt a specific sub-portion of the tree out of automatic detection).

**Describe alternatives you've considered**
I looked into adding `BottomNavigationBar` as a supported type in the `RumUserActionDetector`, but the widget itself knows about its current state, not the tap. I also tried wrapping a few relevant widgets in `RumUserActionAnnotation` but so far can only get the current index, not the tapped index.

**Comment by fuzzybinary** [comment]
Hi @christinachimi 

We are looking into supporting the ability to map or discard specific RUM events, which would allow you to at least discard the ones being automatically generated by the RumUserActionDetector that don't fit. Hopefully that support will be coming soon.

That said, it also sounds like RumUserActionDetector needs some improvement pertaining to how it works with BottomNavigationBar and other GestureDetectors. I'll look into how we can better support these.

Thanks for reporting!

**Comment by fuzzybinary** [comment]
Canceling in progress use actions is now in as part of the release of 1.2.0. You can use the `rumActionEventMapper` to discard user actions you do not want sent to Datadog.

I'm going to leave this open to track improvements to `RumUserActionDetector` around `BottomNavigationBar`.

**Comment by christinachimi** [comment]
Great news, thank you!

**Comment by fuzzybinary** [comment]
Enhancements to RumUserActionDetector that support BottomNavigationBar are now live in 1.3.2
