### ISSUE TITLE
Support for pretty print console logs

### ISSUE THREAD

**Issue by bgenidy** [DataDog/dd-sdk-flutter#298]
Adding support for colored logs when enabling printLogsToConsole. It can be set statically (since I don't think devs are changed log colors on every instance) or passed down the logger configuration and wired into the InternalLogger.

Thinking something exposed on the top level sdk to give modify access to the internal logger similar to verbosity ex: https://github.com/DataDog/dd-sdk-flutter/blob/14e7f5189cdda83718bddc382912290f3c07bdc2/packages/datadog_flutter_plugin/lib/datadog_flutter_plugin.dart#L86

Here is an example of how another SDK supports it, https://github.com/simc/logger/blob/047c410928cf8d39f819458ce48bd8c45a38b65b/lib/src/printers/pretty_printer.dart#L27

And it looks like your code might also be close to supporting it (https://github.com/DataDog/dd-sdk-flutter/blob/14e7f5189cdda83718bddc382912290f3c07bdc2/packages/datadog_flutter_plugin/lib/src/internal_logger.dart#L18) but opted to keep some of the configuration hidden from outside consumers.

**Comment by iTEEECH** [comment]
Hi @fuzzybinary,

Let me bounce off this conversation. Indeed a callback would be nice.

Is it possible to add a log method with a Level as argument ? I looked at it but it is only available for the internal logger.

I managed to add some color and formatting to my logs but impossible to remove it before sending unless I create a specific logger for the moment.

Thanks

**Comment by bgenidy** [comment]
@fuzzybinary yes that would be great! I think any callback or ability to modify the logging view directly would be greatly appreciated.

Currently we use two different loggers to allow local debugging and then datadog for sending the logs out, but it would be great to consolidate both into one.

**Comment by fuzzybinary** [comment]
Hi folks, sorry for the delay on this feature.

v2.0 now has a callback that can be configured on every logger: `customConsoleLogFunction` which you can use to display the log in any format you choose.
