### ISSUE TITLE
Support anonymization data before send

### ISSUE THREAD

**Issue by iTEEECH** [DataDog/dd-sdk-flutter#303]
Are you requesting automatic instrumentation for a framework or library? Please describe.

Framework or library name : datadog_flutter_plugin
Library type: monitoring
Library version: 1.1.1
Is your feature request related to a problem? Please describe.

Hi, 

As part of a professional project dealing with sensitive data, I would like to be able to anonymize personal data before sending it to the Datadog platform please.

This function is already available for Javascript. 

documentation : https://docs.datadoghq.com/real_user_monitoring/browser/modifying_data_and_context/?tab=npm

Thanks

**Comment by fuzzybinary** [comment]
Hi @iTEEECH ,

This is coming. It's the same feature as #297 and #175 and it's currently in progress. Hope to have updates on it very soon.

**Comment by iTEEECH** [comment]
Hi @fuzzybinary,

Oh I hadn't seen it ! Thanks for your answer and the quality of the plugin. 

And I'm taking advantage of this issue as well. For the replay session, is it planned?

Thanks !

**Comment by fuzzybinary** [comment]
We're investigating session replay for mobile, but don't have anything concrete to say about it yet.

**Comment by fuzzybinary** [comment]
This is now available in 1.2.0
