### ISSUE TITLE
[ios] Datadog SDK usage error: `Datadog.initialize()` must be called prior to `Logger.builder.build()`.

### ISSUE THREAD

**Issue by bgenidy** [DataDog/dd-sdk-flutter#328]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Upgraded Flutter from 3.3.10 to 3.7.0 after which upgraded `datadog_flutter_plugin: ^1.2.1` and ran our app. Android version runs fine, ios version throws the following exception

```
Datadog SDK usage error: `Datadog.initialize()` must be called prior to `Logger.builder.build()`.
```

**Steps to reproduce the issue:**
I think just using latest flutter 3.7.0 and latest datadog version 1.2.1 should be able to reproduce the exception shown above.

**Describe what you expected:**
Luckily its a non app boot blocker, but ideally no exception would be thrown so that the logger can send the logs over to datadog servers.

**Additional context**
 - Dart/Flutter version: 3.7.0
 - Android/iOS OS version: io16 
 - Device Model: iphone 14 pro
 - Datadog SDK version: 1.2.1

**Comment by fuzzybinary** [comment]
@bgenidy I can't reproduce this with a simple case -- can you send over your initialization code so I can take a closer look?

Just so I can judge severity, are you seeing logs get dropped or not sent to Datadog? Or are just getting the warning?

**Comment by bgenidy** [comment]
Hi @fuzzybinary this is what my init code looks like

```
WidgetsFlutterBinding.ensureInitialized();
  await environmentSettings.initialize();
  await setupDataDog();

...

Future<void> setupDataDog() async {
  final originalOnError = FlutterError.onError;
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    DatadogSdk.instance.rum?.handleFlutterError(details);
    originalOnError?.call(details);
  };

  await DatadogSdk.instance.initialize(loggerConfiguration);
}
```


It also repros when using `await DatadogSdk.runApp`

It only happens during app startup but subsequent logs get collected fine, and given it happens twice or so, it seems like just the bootup code for iOS might be calling logger once or twice a bit earlier in the flow.

(FYI Im using an emulator iOS 16 not an actual device)

**Comment by fuzzybinary** [comment]
Do you have any code that attempts to create loggers using `DatadogSdk.createLogger`? Something that maybe isn't waiting for initialization to complete?

"Failed to build `Logger`" definitely comes  from the Flutter side, so I'm worried there some race condition where some of your created loggers are not being created properly.

**Comment by bgenidy** [comment]
@fuzzybinary I stepped through the code and I think I have a small piece of code that has consistent repro for you

```dart
import 'package:path_provider/path_provider.dart';
import 'package:datadog_flutter_plugin/datadog_flutter_plugin.dart';

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final originalOnError = FlutterError.onError;
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    DatadogSdk.instance.rum?.handleFlutterError(details);
    originalOnError?.call(details);
  };

  await DatadogSdk.instance.initialize(loggerConfiguration);
  await getApplicationDocumentsDirectory();
}
```

It only happens on iOS (Android is fine). I was able to repro on datadog `1.1.1` package so it doesn't seem like its a recent change of code on datadog sdk side that would have caused it. Subsequent calls to `getApplicationDocumentsDirectory()` does not throw that exception so it might be the first call or so that causes this to happen.

Haven't dug too deep inside the path provider code to see where exactly this is happening, but I suspect it might have to do with some method call that datadog is trying to intercept that causes the issue.

**Comment by fuzzybinary** [comment]
I still can't reproduce with this example (at least on the iOS 16.2 simulator).  Here's my full main with v1.2.1

```dart
void main() async {
  DatadogSdk.instance.sdkVerbosity = Verbosity.verbose;

  final datadogConfig = DdSdkConfiguration(
    clientToken: '<redacted>',
    env: 'prod',
    trackingConsent: TrackingConsent.granted,
    site: DatadogSite.us1,
    loggingConfiguration: LoggingConfiguration(
      sendLogsToDatadog: true,
      printLogsToConsole: true,
    ),
    rumConfiguration: RumConfiguration(
      applicationId: '<redacted>',
    ),
  )..enableHttpTracking();

  WidgetsFlutterBinding.ensureInitialized();
  final originalOnError = FlutterError.onError;
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    DatadogSdk.instance.rum?.handleFlutterError(details);
    originalOnError?.call(details);
  };

  await DatadogSdk.instance.initialize(datadogConfig);
  final directory = await getApplicationDocumentsDirectory();
  DatadogSdk.instance.logs?.info('Directory is ${directory.path}');

  runApp(const MyApp());
}
```

That error message should really only come from a call to `DatadogSdk.createLogger`. If you can you may want to temporarily turn on package debugging (In in VS Code it's under User Settings → Extensions → Dart → Run and Debug) and put a breakpoint on in that method (around `datadog_flutter_plugin.dart:219`). Then see if anything is calling it before initialize does.

**Comment by bgenidy** [comment]
@fuzzybinary can you see if it works with the following configuration (locally I don't send info to DataDog). I just copied the above code you have and swapped the configuration to the one shown below in a new hello world flutter project created using flutter 3.7

```dart
final datadogConfig = DdSdkConfiguration(
    env: 'local',
    trackingConsent: TrackingConsent.granted,
    site: DatadogSite.us1,
    loggingConfiguration: LoggingConfiguration(
      sendLogsToDatadog: false,
      printLogsToConsole: true,
    ),
    clientToken: '',
  )..enableHttpTracking();
```

**Comment by fuzzybinary** [comment]
@bgenidy Yes, I can duplicate now. There's an error message that's being printed to the XCode console during initialization that you're not seeing because of some late biding to the Flutter console:

```
🔥 Datadog SDK usage error: `clientToken` cannot be empty.
```

Even if you're not sending to Datadog, you should still supply your client token, or a least a good fake.

I'll fix the timing of the console binding so this error gets printed properly.

Thanks for the report!

**Comment by bgenidy** [comment]
Thanks @fuzzybinary much appreciated!
