### ISSUE TITLE
Version doesn't working on Flutter web

### ISSUE THREAD

**Issue by iTEEECH** [DataDog/dd-sdk-flutter#334]
Hi, I have no feedback on the version of the application. 

# Steps to reproduce the issue:

I use package info plus to get the version of pubspec.yaml. (I also tried with a static version with a String type '1.0.0'). 
The information doesn't come up on the platform side.

# Additional context

Dart/Flutter version: Flutter 3.7.0, Dart 2.19.0
Flutter web
Browser: All browser
Datadog SDK version: 1.2.1

Thanks

**Comment by fuzzybinary** [comment]
Hi @iTEEECH,

Thanks for reporting. I should have a fix up soon.
