### ISSUE TITLE
Documentation inconsistency: DdRum.setUserInfo not supported

### ISSUE THREAD

**Issue by ebjorklund01** [DataDog/dd-sdk-flutter#344]
**Describe what happened**
This ticket may straddle the line between a feature request and a bug report. We are exploring adding Datadog RUM to our Flutter application and found an error in the documentation. According to the [documentation](https://docs.datadoghq.com/real_user_monitoring/flutter/advanced_configuration/#track-user-sessions), the way to set user info is through `DdRum.setUserInfo` example:

`DatadogSdk.instance.setUserInfo("1234", "John Doe", "john@doe.com");`

However, this method is not currently implemented in the Flutter library. See [`DdRum` class](https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/DdRum-class.html).

How should user info be added to a session? Would we need to set custom attributes using `DdRum.addAttribute`?

**Comment by fuzzybinary** [comment]
Hi @ebjorklund01 

This is just a documentation inconsistency. The method was moved early in development to the main DatadogSdk interface as it affects both RUM and logs. So the sample code is correct but that information above it is not.

The documentation for the correct method is here: https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/DatadogSdk/setUserInfo.html

**Comment by ebjorklund01** [comment]
@fuzzybinary Awesome! Thank you for clarifying!
