### ISSUE TITLE
Semantic Versioning Violation - 1.2.0 causes unexpected build failures

### ISSUE THREAD

**Issue by dustin-graham** [DataDog/dd-sdk-flutter#346]
**Describe what happened**
Builds are broken when running `pub upgrade`. This should not happen. Pub dependencies should follow Semantic Versioning strictly to avoid unexpected breakages. See https://semver.org/

The specific problem here is that a breaking API change was introduced on 1.2.0 but only the minor version number changed. Here are the rules:
1. MAJOR - required for any public API change (like the one introduced by 1.2.0)
2. MINOR - required for any backward compatible changes
3. PATCH - required for any internal bug fixes

This library introduced a breaking API change which should have required the version to change to 2.0.0 at least. If you don't want to bump the MAJOR version you have to allow for a backward compatible API.

In order to fix this issue you need to publish a new MINOR version which provides a backward compatible interface that will allow any version < 2.0.0 to compile. Then you will need to publish a 2.0.0 version with the extra backward compatible interface removed (as it is now).

**Steps to reproduce the issue:**
  - Write code against 1.0.1 (exact constrain version)
  - Loosen version constraints to `^1.0.1`
  - Run `pub upgrade`
  - Try to build the app

**Describe what you expected:**
The app should build without requiring code changes. Pub follows SemVer. Please see this for more dart-package specific information: https://dart.dev/tools/pub/versioning#semantic-versions. It's very important to follow these conventions.

**Additional context**
 - Dart/Flutter version: any
 - Android/iOS OS version: any
 - Device Model: any
 - Datadog SDK version: migrating to 1.0.1 (or 1.1.0) -> 1.2.0
 - Versions of any other relevant dependencies: none

**Comment by dustin-graham** [comment]
If anyone is running into the same build issue, the work around is to depend on the specific version you want. The complication for our project is that datadog is consumed inside of a shared internal library. Our internal consumer builds are now broken if any of them use `^` in their datadog version constraints.

**Comment by fuzzybinary** [comment]
Hi @dustin-graham, thanks for the report. 

We’ll do our best not to violate semver rules in the future, but since fixing this would force us to violate semver rules again, I'm going to close this as won’t fix. As you pointed out, you can pin to 1.1.1 until you are ready to update to 1.2.
