### ISSUE TITLE
Plugin exception when running web app

### ISSUE THREAD

**Issue by jorgelrj** [DataDog/dd-sdk-flutter#386]
Hi there, I'm testing the plugin on a web application I develop and a I came across this exception when trying to set up the app:
`Error: MissingPluginException(No implementation found for method setSdkVerbosity on channel datadog_sdk_flutter)`

That's my main code: 
```
final configuration = DdSdkConfiguration(
        clientToken: ***,
        env: injection.flavor.environment.name,
        site: DatadogSite.us1,
        trackingConsent: TrackingConsent.granted,
        nativeCrashReportEnabled: true,
        loggingConfiguration: LoggingConfiguration(
          sendNetworkInfo: true,
          printLogsToConsole: true,
        ),
        rumConfiguration: RumConfiguration(
          applicationId: ***,
        ),
      );

      final ddsdk = DatadogSdk.instance;
      ddsdk.sdkVerbosity = Verbosity.verbose;

      await DatadogSdk.instance.initialize(configuration);

      FlutterError.onError = (FlutterErrorDetails details) {
        FlutterError.presentError(details);
        ddsdk.rum?.handleFlutterError(details);
      };

      runApp(
        AppWidget(
          ...
        ),
      );
```

Even without setting the sdkVerbosity or providing a logging configuration, the exception happens 

**Additional context**
 - Dart/Flutter version: 
 
 ```
Flutter 3.7.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90c64ed42b (2 weeks ago) • 2023-03-21 11:27:08 -0500
Engine • revision 9aa7816315
Tools • Dart 2.19.5 • DevTools 2.20.1
```
 - Datadog SDK version:
 `  datadog_flutter_plugin: ^1.3.2`

**Comment by fuzzybinary** [comment]
Hey @jorgelrj  

This one really stumps me. If you're not setting `sdkVerbosity` there should be no reason for you to end up at that call stack. More importantly, on web we should be replacing the Platform in such a way that it should never use the method channel.

I have one other report of this, but it's with Release mode only. Is that true for you as well?

**Comment by jorgelrj** [comment]
@fuzzybinary Yes, sorry I forgot to mention it. Only happens on the deployed app built in release mode. Testing it locally works fine

**Comment by fuzzybinary** [comment]
@jorgelrj Does testing the same build work locally, but not when deployed?

If you run:
```bash
flutter build web --release --web-renderer canvaskit --pwa-strategy=none
cd build/web
python3 -m http.server 8080
```

And go to the site locally, does it work? If so, I'm wondering if where you're deploying is doing something weird.

**Comment by jorgelrj** [comment]
@fuzzybinary

I did two tests here, I built the app running only `flutter build web` and it it worked on the local server, but when I added the `--source-maps` flag that I use on my ci flow, I got the same exception again

**Comment by fuzzybinary** [comment]
@jorgelrj I can't reproduce this, but it looks like it might be something related to issues with the `generated_plugin_registrant.dart` file, similar to this issue https://github.com/fluttercommunity/plus_plugins/issues/1270

The fix for them was updating the plugin to specify versions of Flutter > 2.11, but at the moment we support 2.8/

If you're so inclined, you can pull the repo locally, change the `pubspec.yaml` to set `flutter: ">=2.11.0`, depend on that module from the path and see if that fixes your issue.

If it does let me know and I'll see if we can update to support 2.11.0+ and publish a new version.

**Comment by jorgelrj** [comment]
Hey @fuzzybinary,

Just test it here and setting `flutter: ">=2.11.0"` did get it to work 👍

**Comment by fuzzybinary** [comment]
Okay, thanks @jorgelrj .  I'll see if we can update our min-version for 1.4

**Comment by liranzairi** [comment]
@fuzzybinary I'm getting the exact same error in web only in release mode (not in debug mode)

My initialization code:
```dart
final configuration = DatadogConfiguration(
  clientToken: ***,
  env: 'staging',
  service: ***,
  site: DatadogSite.us1,
  nativeCrashReportEnabled: true,
  loggingConfiguration: DatadogLoggingConfiguration(),
);
await DatadogSdk.instance.initialize(configuration, TrackingConsent.granted);
```

**Additional context:**
Flutter version: 3.16.2
Dart version: 3.2.2
Environment: sdk: '>=3.1.2 <4.0.0'
Datadog package version: datadog_flutter_plugin 2.3.0

**Comment by fuzzybinary** [comment]
Weird, I wonder if something regressed on the Flutter side. I'll reopen this and take a look as soon as I can.

**Comment by fuzzybinary** [comment]
Hi @lirantzairi,

I just checked this quickly on Flutter 3.19.2 and 3.16.2 didn't receive the error.  How are you trying to access your Flutter web app? Opening the html usually does not work, so you have to run a web server in your `build/web` directory (I usually just use the built in python web server for testing).

If you're still having the issue, can you give me any more information about your setup that might help me determine what's going wrong?

**Comment by opsb** [comment]
Same issue with `flutter 3.19.3` and
```
datadog_flutter_plugin: ^2.3.0
datadog_tracking_http_client: ^2.1.0
```

**Comment by liranzairi** [comment]
> Hi @lirantzairi,
> 
> I just checked this quickly on Flutter 3.19.2 and 3.16.2 didn't receive the error. How are you trying to access your Flutter web app? Opening the html usually does not work, so you have to run a web server in your `build/web` directory (I usually just use the built in python web server for testing).
> 
> If you're still having the issue, can you give me any more information about your setup that might help me determine what's going wrong?

Hi @fuzzybinary, I use Firebase Hosting for deploying my web app. By "release mode" I meant to say that it happens in a fully deployed web app.

**Comment by fuzzybinary** [comment]
Hi folks --

Sorry for the delay here, but I still cannot reproduce.

After building, can you check that your `generated_plugin_registrant.dart` contains the following:

```dart
DatadogSdkWeb.registerWith(registrar);
registrar.registerMessageHandler();
```

Also, I'm seeing reports from others with similar issues that a clean rebuild occasionally fixes the issue for them. Can you confirm that doesn't work?

**Comment by fuzzybinary** [comment]
Going to close this as I was unable to reproduce and haven't heard of anyone else having this issue.
