### ISSUE TITLE
RUM and Traces not working with package Dio

### ISSUE THREAD

**Issue by rodrigopequeno** [DataDog/dd-sdk-flutter#402]
Thanks for taking the time for reporting an issue!

**Describe what happened**
When using ```datadog_tracking_http_client```, I can't make requests made with Dio be tracked. I currently use Dio interceptors for this, but I can't do Trace using the interceptor to pass the parameters through the header.

**Steps to reproduce the issue:**
- Using the packages versions informed below
- I run the application and make two requests, one using the ```http``` package and the other using ```dio``` package
- In Datadog RUM, only the request made by HTTP is displayed

**Describe what you expected:**
I hope that when using ```datadog_tracking_http_client``` and o ```dio``` the requests are captured in the RUM and that the trace can be performed too

**Additional context**
 - Dart/Flutter version: 3.7.11
 - Android/iOS OS version: Android 13
 - Device Model: POCO F3
 - Datadog SDK version: 1.3.2
 - Versions of any other relevant dependencies:
   - datadog_tracking_http_client: 1.2.1
   - dio: 5.1.1

**Comment by fuzzybinary** [comment]
Hi @rodrigopequeno,

The tracking_http_client should be compatible with Dio so far as I know. Are you doing anything when setting up Dio that would make it not use the default `dart:io` `HttpClient`? By default, both `http` and `dio` use the same `dart:io` requests.

One thing to double check is your tracing sampling rate. By default it's set to 20%, so it's possible you've just gotten unlucky with Dio on the sampling.

**Comment by rodrigopequeno** [comment]
I don't think I did any specific configuration that makes ```dio``` not use ```dart:io.```
I ran the tests passing ```100``` in [tracingSamplingRate](https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/RumConfiguration/tracingSamplingRate.html).

**Comment by rodrigopequeno** [comment]
Hi @fuzzybinary

I made a demo application and it is working correctly in it. I'm going to look deeper into the app that's having the problem to try to identify the problem.

**Comment by fuzzybinary** [comment]
@rodrigopequeno Would you be able to send over a sample that reproduces the issue? I'm not able to replicate with a simple case.

Another possibility to check, are you seeing the resources in Datadog, but not the traces? If that's the case, double check that your `firstPartyHosts` parameter is being set correctly.

**Comment by rodrigopequeno** [comment]
Hello @fuzzybinary,

Sorry for the delay, got very busy. I'm going to close this issue because I've updated the versions and it's working correctly now and I couldn't pinpoint the reason, being very project specific.

I didn't dig too deep, but my guess was around APIM and authentication, as unauthenticated endpoints were tracked.

Finally, thanks for the help.

Updates:
- Dart/Flutter version: 3.10.0
- Datadog SDK version: 1.4.0
- Versions of any other relevant dependencies:
  - datadog_tracking_http_client: 1.2.1
  - dio: 5.1.2
