### ISSUE TITLE
Errors are not appearing in Logs [Error Tracking]

### ISSUE THREAD

**Issue by yonjans** [DataDog/dd-sdk-flutter#408]
**Describe what happened**
After integrating Flutter plugin, we can see error logs in `Error Tracking` of `UX Monitoring` but same error logs are not appearing in `Error Tracking` of `Logs`. We can see error logs coming from APM in `Error Tracking` of `Log` though.

**Steps to reproduce the issue:**
Configure Datadog:

```
  final datadogConfiguration = DdSdkConfiguration(
    clientToken: currentPlatform() == Platform.android
        ? datadogConfig.androidClientToken
        : datadogConfig.iosClientToken,
    env: datadogConfig.flavorName,
    trackingConsent: TrackingConsent.granted,
    site: DatadogSite.eu1,
    serviceName: datadogConfig.serviceName,
    nativeCrashReportEnabled: true,
    rumConfiguration: RumConfiguration(
      applicationId: currentPlatform() == Platform.android
          ? datadogConfig.androidRumApplicationId
          : datadogConfig.iosRumApplicationId,
    ),
    loggingConfiguration: LoggingConfiguration(
      printLogsToConsole: true,
      sendNetworkInfo: true,
    ),
    uploadFrequency: UploadFrequency.frequent,
  );
```

**Describe what you expected:**
We would like to see errors reported from RUM app also in `Error Tracking` of `Logs` as it does for APM Errors.

**Additional context**
 - Dart/Flutter version: `2.17.1/3.0.1`
 - Android/iOS OS version: Any
 - Device Model: Any
 - Datadog SDK version: `1.1.0`
 - Versions of any other relevant dependencies:

**Comment by fuzzybinary** [comment]
Hi @yonjans ,

The RUM SDK doesn't send errors to both RUM and Logs by default. If you're specifically looking to send uncaught errors to logs, you should replace `runApp` to send errors to Logs:

```dart
return runZonedGuarded(() async {
      WidgetsFlutterBinding.ensureInitialized();
      final originalOnError = FlutterError.onError;
      FlutterError.onError = (details) {
        DatadogSdk.instance.rum?.handleFlutterError(details);
        originalOnError?.call(details);
      };

      await DatadogSdk.instance.initialize(configuration);
      DatadogSdk.instance
          .updateConfigurationInfo(LateConfigurationProperty.trackErrors, true);

      runner();
    }, (e, s) {
      DatadogSdk.instance.logs?.error(
        e.toString(), 
        errorKind: e.runtimeType.toString(),
        errorStackTrace: s,
      ),
      DatadogSdk.instance.rum?.addErrorInfo(
        e.toString(),
        RumErrorSource.source,
        stackTrace: s,
      );
    });
```

If you're looking to track network errors in Logs, I'll need to add an option / enhancement to the datadog_tracking_http_client to forward those errors.

**Comment by yonjans** [comment]
Thanks @fuzzybinary 

It worked. We were in an impression that sending error logs to RUM should automatically index in Logs also.
For now, we are not in need to track network error logs but may be in the future or when the time suits you :)

However, we could not see these error logs in Logs -> Error Tracking. We want to get all the errors from our Flutter app in Error Tracking (Beta) of the Logs in Datadog. Could there be any flags that stops from indexing error logs in Error Tracking? Some of our error logs from backend are indexed in there but not we could not find out the reason for Flutter error logs.

**Comment by fuzzybinary** [comment]
We purposefully don't send to both, but in reality we should probably set it as an easy to use option.

I'll need to do a bit of research to determine if there's anything that would prevent the errors from showing in the ET for Logs beta. So far as I'm aware, so long as you're sending the error to logs, it should be index and viewable in the ET interface.

**Comment by yonjans** [comment]
@fuzzybinary I am reaching to Datadog support for this. Thanks.
