### ISSUE TITLE
Expose a way to get the Session Id

### ISSUE THREAD

**Issue by almovsesanso** [DataDog/dd-sdk-flutter#442]
It looks like there'a way to get the session id through the web SDK but I couldn't find a similar way to get it from Flutter. I need it for the same purpose as the web app, to allow the user to contact us when they're encountering a problem.

https://github.com/DataDog/browser-sdk/issues/390

**Comment by fuzzybinary** [comment]
Hi @almovsesanso thanks for the suggestion. We're looking into it!

**Comment by almovsesanso** [comment]
> Hi @almovsesanso thanks for the suggestion. We're looking into it!

Thanks @fuzzybinary. Do you know if there's an indirect way to get the session id currently using flutter?

**Comment by fuzzybinary** [comment]
It's not a great workaround, but you can use a `RumViewEventMapper` and inspect `RUMViewEvent.session.id` and get the session after we send the first batch to Datadog.

**Comment by utkarshagarwal** [comment]
@fuzzybinary as suggested we used view event mapper to extract the session id. It works perfectly for our use case for iOS simulator and android (devices and simulator both) but fails on iOS real device. Any particular reason you can think of?
The event mapper is not getting called at all on device.

**Comment by fuzzybinary** [comment]
Not that I can think of, no, but I will look into it. I was able to get the callback to fire in a debug build on device, but I will try a release build on device later today.

Is there anything else strange about your setup? How are you checking that the mapper is firing?

**Comment by fuzzybinary** [comment]
@utkarshagarwal I just tested our example application on an iPhone 11 and didn't have any issues getting a mapper callback. Note that the mappers are called immediately before we send data to Datadog, and there are situations (like low battery) where the SDK prefers to wait to send data, which is why this approach to getting session id isn't ideal....

**Comment by almovsesanso** [comment]
> @utkarshagarwal I just tested our example application on an iPhone 11 and didn't have any issues getting a mapper callback. Note that the mappers are called immediately before we send data to Datadog, and there are situations (like low battery) where the SDK prefers to wait to send data, which is why this approach to getting session id isn't ideal....

Thanks for replying, Jeff.

Do you know if there's a way to one-off force the SDK to send events?

**Comment by fuzzybinary** [comment]
Unfortunately no, there's no public `flush` or similar.

We are looking to add an official session id accessor very soon though. Sorry for the delay!

**Comment by MauriMiguez** [comment]
Hi! Any update on this Issue? Do you have a timeline for this?

**Comment by fuzzybinary** [comment]
Hi @MauriMiguez 

It's still on our roadmap. Can't commit on a timeline at the moment but hopefully soon. Sorry for the delay!

**Comment by fuzzybinary** [comment]
This is now available in 2.2.0.
