### ISSUE TITLE
[Flutter Module][iOS] Multiple commands produce Datadog.framework

### ISSUE THREAD

**Issue by 4rthurmonteiro** [DataDog/dd-sdk-flutter#443]
**Describe what happened**
Include any error message or stack trace if available.

We use a Flutter Module in our native ios app using the xcframeworks, running `flutter build ios-framework ...`.  When we  implemented the datadog using the attachToExisting approach we had this error `Multiple commands produce Datadog.framework` because in the iOS project the datadog pods are included.

**Steps to reproduce the issue:**

Go to examples/native-hybrid-app and in the flutter module use the Option B ou C from https://docs.flutter.dev/add-to-app/ios/project-setup .

**Describe what you expected:**

The same result from the Option A from https://docs.flutter.dev/add-to-app/ios/project-setup .

**Additional context**
 - Dart/Flutter version: Flutter 3.10.3 and Dart 3.0.3
 - Android/iOS OS version: iOS 15
 - Device Model: Iphone 6S
 - Datadog SDK version: newest
 - Versions of any other relevant dependencies: Xcode 14.2

**Comment by fuzzybinary** [comment]
Hi @4rthurmonteiro ,

Thanks for reporting, I'll look into it. I'm not exactly sure how I can support Option B or C without supplying a completely separate package, since I don't think there's a way for me to exclude the pod dynamically, but maybe I'm just missing some option.

Would it be possible to remove the Datadog iOS SDK from the app side, and allow the `datadog_flutter_plugin` to  framework to supply it instead?

**Comment by 4rthurmonteiro** [comment]
Hi @fuzzybinary

I will try remove the Datadog iOS SDK from the app side.

**Comment by 4rthurmonteiro** [comment]
@fuzzybinary when i removed the Datadog iOS SDK from app side a received this error below:

<img width="1092" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/22081436/1f972584-d241-4c4b-8c44-eef192870fcb">

**Comment by fuzzybinary** [comment]
Okay, I'll continue to investigate a fix.

**Comment by p-mazhnik** [comment]
@4rthurmonteiro 
As a workaround, can you try deleting `Datadog.framework` produced by `flutter build ios-framework` command?
from `flutter_module/build/ios/framework/**/Datadog.xcframework`

**Comment by 4rthurmonteiro** [comment]
Hi @p-mazhnik

I tried deleting Datadog.framework but i received a lot of errors called `Undefined symbols for architecture arm64` .

**Comment by p-mazhnik** [comment]
@4rthurmonteiro 
Ok. Then the best option will be to link only `App.xcframework` (& embed) and `FlutterPluginRegistrant.xcframework` (without embedding). 
(So don't include Datadog-related frameworks: Datadog, datadog_flutter_plugin, DatadogCrashReporting and DictionaryCoder)

Main step will be to add `datadog_flutter_plugin` manually to Podfile:
```ruby
pod 'datadog_flutter_plugin', :path => '../flutter_module/.ios/.symlinks/plugins/datadog_flutter_plugin/ios', :inhibit_warnings => true
```

**Comment by 4rthurmonteiro** [comment]
@p-mazhnik i have some problems with this approach. So i followed like you did in https://github.com/flutter/flutter/issues/114692 and worked! 

How do you distribute your pods? Locally or remotely?

**Comment by fuzzybinary** [comment]
Hi folks -- is there something Datadog needs to change here or something we should  add to our documentation to assist others with this scenario?

**Comment by 4rthurmonteiro** [comment]
@fuzzybinary i think Option B and C is not possible use the attached aproach. So just add this observation in the example.

**Comment by fuzzybinary** [comment]
Closing with new documentation. If there ends up being a workaround we'll open another issue to track documenting the workaround.
