### ISSUE TITLE
MissingPluginException(No implementation found for method createLogger on channel datadog_sdk_flutter.logs)

### ISSUE THREAD

**Issue by francescreig** [DataDog/dd-sdk-flutter#446]
Thanks for taking the time for reporting an issue!

**Describe what happened**
Hi! When I try to perform a widget test, it appears this message
`MissingPluginException(No implementation found for method createLogger on channel datadog_sdk_flutter.logs)` and it does crash the test. Only happens when testing, though.

**Steps to reproduce the issue:**
Create a widget test with the datadog_flutter_plugin installed.

**Describe what you expected:**
I expect not to have this error when launching the tests.

**Additional context**
 - Dart/Flutter version: Dart 3.0.3 / Flutter 3.10.4
 - Android/iOS OS version: iOS 15.2
 - Device Model: (simulator)
 - Datadog SDK version: datadog_flutter_plugin on version 1.5.1 (latest now)
 - Versions of any other relevant dependencies:

**Comment by francescreig** [comment]
Perfect, thanks @fuzzybinary! The second method it worked it nicely! I also added `datadog_sdk_flutter.logs` and `datadog_sdk_flutter.rum`.

**Comment by fuzzybinary** [comment]
Great! Glad to hear it worked. I'm going to reopen this to track the work to add a simpler no-op implementation for testing, and supply a public method to enable it.

**Comment by fuzzybinary** [comment]
No op implementation is now available in 1.6.0
