### ISSUE TITLE
datadog_tracking_http_client requires http < 1.0.0

### ISSUE THREAD

**Issue by scopendo** [DataDog/dd-sdk-flutter#457]
The `datadog_tracking_http_client` package has `http` package version ^0.13.5 as an explicit dependency.  Now that the Dart team have released 1.x versions of the http package, we get conflicts when using other packages (such as google_fonts) that have specified `^1.0.0` as the version.

Adding a dependency override to set http explicitly to `^1.0.0` seems to work OK.

**Steps to reproduce the issue:**
Create a project with both datadog_tracking_http_client 1.3.1 and google_fonts 5.1.0.

**Describe what you expected:**
A later version of `datadog_tracking_http_client` that works with http 1.x versions.

**Additional context**
 - Dart/Flutter version: 3.10.6

**Comment by fuzzybinary** [comment]
This is fixed and deployed as `datadog_tracking_http_client` 1.4.0
