### ISSUE TITLE
`uuid` library 4.0.0 support

### ISSUE THREAD

**Issue by mikhael28** [DataDog/dd-sdk-flutter#472]
Hi there! I'm writing to ask the dd team to look into adding dependency support for the 4.0 release of the `uuid` package on pub. Currently, 1.6.0 allows ^3.0.5 but will not allow the presence of 4.0, and thus preventing me from upgrading certain other packages. From my understanding, the 4.0 release has some breaking changes but preserves backwards compatibility for their base APIs. The breaking changes are mostly for more complex usage.

Changelog for 4.0 is here, cheers. https://pub.dev/packages/uuid/changelog

**Comment by fuzzybinary** [comment]
Hi @mikhael28,

Although the basic interface is the same, upgrading to 4.0 is potentially a breaking change for others that depend on the same library.

We're currently working on plugin v2 which will depend on the new iOS and Android v2 SDKs, and I'll make sure upgrading `uuid` to 4.0 is part of that. Can't give an exact timeline yet but hopefully shouldn't be too long.

**Comment by mikhael28** [comment]
@fuzzybinary that sounds great to me! Thanks for responding, will leave it up to you if you want to close this Issue. Other people may have the same question.

**Comment by fuzzybinary** [comment]
v2.0 now has the UUID package at a constraint of `^4.0.0`

**Comment by mikhael28** [comment]
You are a boss! I just upgrade to 2.0, will let you know if I see any issues. No news is good news :)
