### ISSUE TITLE
Error report: handle_signal ANR triggered by slow operations in blamed thread

### ISSUE THREAD

**Issue by Lee-Glen** [DataDog/dd-sdk-flutter#487]
**Describe what happened**
```
ANR triggered by slow operations in blamed thread
0 libc.so syscall + 32
1 libc.so __futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 148
2 libc.so NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*) + 392
3 libc.so pthread_mutex_lock + 264
4 split_config.arm64_v8a.apk write_crash_report + 76
5 split_config.arm64_v8a.apk handle_signal + 136
``` 

**Steps to reproduce the issue:**

**Describe what you expected:**
Datadog SDK should not crash the app

**Additional context**
 - Dart/Flutter version: 3.0.5/3.10.5
 - Android/iOS OS version: Multiple Android versions
 - Device Model: All Android devices
 - Datadog SDK version: 1.6.0
 - Versions of any other relevant dependencies: -

**Comment by fuzzybinary** [comment]
Hi @Lee-Glen,

We'll definitely take a look into it. Do you have any more information about how to reproduce this?

**Comment by fuzzybinary** [comment]
Hi @Lee-Glen,

We took some steps in our NDK signal catcher to avoid a potential deadlock / ANR, which has now been integrated into Flutter 2.1.0. Closing for now but if you continue to see this issue please let us know.
