### ISSUE TITLE
Add verbose level log

### ISSUE THREAD

**Issue by jtromo** [DataDog/dd-sdk-flutter#494]
datadog_flutter_plugin: ^1.6.0

The `Verbosity` enum allows for a `verbose` level of logging, but the `DdLogs` class only allow for logging `debug`, `info`, `warn`, and `error` level logs raising the question what the point is for having that level. 

`enum Verbosity { verbose, debug, info, warn, error, none }` 

**Describe the solution you'd like**
Add the ability to log at a `verbose` level.

**Comment by fuzzybinary** [comment]
`Verbosity` is unfortunately playing double duty that it shouldn't be, both as a level for the internal native SDKs and as a level for Datadog logs.

In this case, `Verbosity.verbose` is used internally to ask the native SDKs to log more verbosely, and Datadog's log backend would map a `verbose` level to `debug` anyway.

v2 will split the logging levels of the SDK (`CoreLoggerLevel`) from the log level of logs sent to Datadog (`LogLevel`), at which point `verbose` will be removed.
