### ISSUE TITLE
[Version: 2.0.0]Unable to set `remoteLogThreshold` on `DatadogLoggerConfiguration` due to private enum

### ISSUE THREAD

**Issue by bgenidy** [DataDog/dd-sdk-flutter#518]
Hi, I recently upgraded to the latest datadog version and noticed a few changes in the interfaces. One of them was the removal of Verbosity in favor of `LogLevel`.

While trying to set `LogLevel` I noticed that its set to private which forces me to use the default value.

**Describe what happened**
Include any error message or stack trace if available.

**Steps to reproduce the issue:**
1. Upgrade or start a new flutter project with version 2.0.0 of the datadog_flutter_plugin
2. Try setting the `LogLevel`
```dart
DatadogLoggerConfiguration(
        remoteLogThreshold: LogLevel.info,
        remoteSampleRate: 100,
        networkInfoEnabled: true,
        name: name)
```

**Describe what you expected:**
To be able to set the LogLevel of the DatadogLoggerConfiguration

**Additional context**
 - Flutter version: 3.16.0
 - Android/iOS OS version: N/A
 - Device Model: N/A
 - Datadog SDK version: 2.0.0
 - Versions of any other relevant dependencies:

**Comment by fuzzybinary** [comment]
Hi @bgenidy,

This should be fixed in 2.1.0.

Please let me know if you have any issues!
