### ISSUE TITLE
[Docs - datadog_flutter_plugin] README has an image which doesn't work

### ISSUE THREAD

**Issue by Gummiees** [DataDog/dd-sdk-flutter#520]
Thanks for taking the time for reporting an issue!

**Describe what happened**

In this line, the README seems like should have an image:

https://github.com/DataDog/dd-sdk-flutter/blob/datadog_flutter_plugin/v2.0.0/packages/datadog_flutter_plugin/README.md?plain=1#L51

```md
{{< img src="real_user_monitoring/flutter/flutter-new-application.png" alt="Create a RUM application in Datadog workflow" style="width:90%;">}}
```

I've forked the repo and updated the code so it would be a working HTML image tag, but the path does not work since it's a relative path.

**Steps to reproduce the issue:**

**Describe what you expected:**

To see the image working, which from the image description should be showing how to create a RUM application in Datadog workflow.

**Additional context**
 - Dart/Flutter version:
 - Android/iOS OS version:
 - Device Model:
 - Datadog SDK version: 2.0.0 (same happening on `develop`)
 - Versions of any other relevant dependencies:

**Comment by fuzzybinary** [comment]
Hi @Gummiees ,

Thanks for pointing this out.

We're still in the process of moving most of our documentation over to the [official documentation site](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter/) and deciding which portions should remain in the README.

I'll remove the image and replace it with a link to the official documentation.
