### ISSUE TITLE
Attribute with key `error` not populating in backend on Android

### ISSUE THREAD

**Issue by btrautmann** [DataDog/dd-sdk-flutter#527]
**Describe what happened**

We've noticed that on Android, we are not receiving all of our attributes in the Datadog logs on the backend. Specifically, it seems an attribute with the key `error` is not being propagated. We send the same payload on iOS and Android, but only the latter is having the issue.

**Steps to reproduce the issue:**

Invoke the following on a `Ddlogs` object:
```dart
_logger.error(message, attributes: attributes);
```
where `attributes` is a `Map` containing the keys `error` and `stackTrace`, where `error` is any `Exception`'s `toString()` value and `stackTrace` is any `StackTrace`'s `toString()` value.

**Describe what you expected:** 

In the Datadog logs, you should see the following on the log (with the value being different based on your `Exception` type):

![Screenshot 2023-12-05 at 15 08 02](https://github.com/DataDog/dd-sdk-flutter/assets/8343465/4c00226f-3a1a-42a1-b82e-fbfaced48655)

The above is an iOS log value, but Android does not report the same.

**Additional context**
 - Dart/Flutter version: 
 ```console
Flutter 3.10.7 • channel unknown • unknown source
Framework • revision e285328a69 (4 months ago) • 2023-08-17 17:55:17 -0700
Engine • revision 077a732ef4
Tools • Dart 3.0.7 • DevTools 2.23.1
```
 - Android/iOS OS version: Android 14 (tested on other versions as well)
 - Device Model: N/A
 - Datadog SDK version: 1.5.1
 - Versions of any other relevant dependencies: N/A

**Comment by fuzzybinary** [comment]
Hi @btrautmann ,

Thanks for reporting, I'll take a look into why this is happening and get back to you.

**Comment by fuzzybinary** [comment]
Hi @btrautmann ,

This looks like a minor difference in how the native iOS and Android SDKs approach some reserved properties in logging, and I'm talking with the team about how we want to approach the problem.  The complete list of Android's "reserved properties" are:

```
["status", "service", "message", "date", "logger", "_dd", "usr", "network", "error", "ddtags"]
```

Stack trace doesn't appear to be included as reserved though, are you sure it's not being sent?

If you can, it's better to add your error message, kind, and stack trace to the properties on individual log calls. E.g.:

```dart
_logger.info('message', errorMessage: error.toString(), errrorKind: error.runtimeType, errorStackTrace: st);
```

This ensures we'll put everything in the right place.

**Comment by btrautmann** [comment]
> Stack trace doesn't appear to be included as reserved though, are you sure it's not being sent?

Yes, `stackTrace` is making it to the backend. I'll chat with the team to see if we can move our bits of data around (I imagine we can!), and circle back here tomorrow. Thanks for looking into this @fuzzybinary!

**Comment by fuzzybinary** [comment]
I'm going to close this because it's expected (if inconsistent) behavior. I'll look into getting these reserved attributes better documented, and make sure there's a prominent warning in dev when you're using them.

**Comment by btrautmann** [comment]
Shoot, sorry I never got back to you here. We ended up shipping the change you suggested and things are working good on our side now 👍 Thanks!
