### ISSUE TITLE
How can I customize the error grouping?

### ISSUE THREAD

**Issue by theusmoraes** [DataDog/dd-sdk-flutter#539]
While reviewing the current error tracking functionality within datadogRum, I noticed that in some cases, it is grouping together different errors, which is not desirable for my use case. In my search for a solution, I consulted the [documentation](https://docs.datadoghq.com/real_user_monitoring/error_tracking/custom_grouping/) and identified the option to use a fingerPrint to prevent the grouping of these unwanted errors.

However, upon exploring the implementation in Flutter, I realized that this functionality does not seem to be available. I would like to know the best approach to handle this situation. What would be the appropriate way to proceed or implement an alternative solution to work around this issue?

**Comment by plousada** [comment]
Hi @theusmoraes, indeed this functionality is missing from our current Flutter offering. 
Unfortunately there's no workaround I can propose.

I can share that it's in our plans to release support to set `fingerprint` on errors in Q1.

**Comment by fuzzybinary** [comment]
Custom fingerprinting should now be available in 2.4.0 by adding `DatadogAttributes.errorFingerprint` to log and calls and to `addError*` calls in RUM. You can also modify the error fingerprint in event mappers as well.

This isn't in the official documentation yet, but we'll add it soon.

Let us know know if you see any issues!
