### ISSUE TITLE
[RUM][Web] View's custom attribute is not being sent

### ISSUE THREAD

**Issue by toussam** [DataDog/dd-sdk-flutter#565]
Hi²,

I'm opening a second ticket for another issue that we noticed during the #564's investigation.

**Describe what happened**
We noticed that if we set up a custom attribute to a specific view event using the startView method's third parameter (attributes) then this last one won't be displayed in Datadog's RUM. **This is only true when using Flutter Web.**

**Steps to reproduce the issue:**
- track a view using the startView method and provide a custom attribute while doing so
- launch your web app
- notice that the custom attribute is missing from the rum's view event

**Describe what you expected:**
The view event's should contain the provided custom attribute.

Additional context

Dart/Flutter version: 3.2.6 / 3.16.9
Android/iOS OS version: Web issue only!
Device Model: N/A
Datadog SDK version: 2.2.0
Versions of any other relevant dependencies: N/A

Thanks² in advance for your investigation and future response. 🙏

Best regards,

**Comment by fuzzybinary** [comment]
Hi @toussam ,

This is actually a known limitation of Datadog's Flutter Web implementation that was missed in the list of limitations in the documentation. I will add it.

If this is something you need, please reach out to your CSM to let them know to raise it as a feature request.

**Comment by toussam** [comment]
Hi @fuzzybinary,

We will contact our CSM as suggested.

Thanks for your response. I'm now closing this issue.
