### ISSUE TITLE
[iOS] Variant doesn't appear to be applied to logs

### ISSUE THREAD

**Issue by ellis-cot** [DataDog/dd-sdk-flutter#568]
### Describe the bug

Since symbolication appears to use the variant to find the correct symbols, this causes "Symbolication failed" errors for logs with stack traces.

We're obfuscating our build and uploading the symbols/maps with the `--flavor` argument as recommended here: https://docs.datadoghq.com/real_user_monitoring/error_tracking/mobile/flutter/#advanced-configuration---flavors-and-build-numbers. 
We also supply the `flavor` parameter to the DatadogConfiguration object.

Android logs are tagged with the variant and are symbolicated correctly, we get an error message for iOS logs.

### Reproduction steps

Obfuscate a build and upload the symbols with the `--flavor` parameter.
Initialise the DataDog SDK instance with flavor set.
Create a log that includes a stack trace.
See if the log has been symbolicated.

### Expected behavior

Stack traces are symbolicated and the logs are tagged with the variant

### Affected SDK versions

2.2.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Flutter Version

3.16.5

### Setup Type

Flutter application

### Device Information

iOS

**Comment by fuzzybinary** [comment]
Hi @ellis-cot,

Thanks for reporting. This does seem to be the case. I'll need to add variant reporting to the iOS SDK and I'll release a fix to Flutter ASAP.

Sorry for the inconvenience!

**Comment by ellis-cot** [comment]
Marvellous, thanks for the swift response @fuzzybinary

**Comment by fuzzybinary** [comment]
This should now be available in 2.4.0. Please let me know if you see any issues.
