### ISSUE TITLE
Upgrade datadog_flutter_plugin js dependency to 0.7.x

### ISSUE THREAD

**Issue by kwent** [DataDog/dd-sdk-flutter#572]
### Feature description

Upgrade `datadog_flutter_plugin` `js` dependency to 0.7.x. https://pub.dev/packages/js/changelog

### Proposed solution

Upgrade `datadog_flutter_plugin` `js` dependency to 0.7.x. https://pub.dev/packages/js/changelog

**Comment by fuzzybinary** [comment]
Hey @kwent ,

Is there a specific fix you need the update for (other than making version solving happy?)

I'll take a look into it. Despite `js` marking this as a minor version update, it contains breaking changes, and I need to make sure this won't break downstream dependencies requiring us to issue a major version update.  Depending, I may be able to loosen our constraint to `>=0.6.3 <0.8.0`.

**Comment by fuzzybinary** [comment]
Alternately, would it affect you if we moved over to the now preferred `js_interop` package?

**Comment by kwent** [comment]
Hi @fuzzybinary, it's just clashing with `flutter_native_splash` `2.3.13`. And i think a lot of us are using this plugin :) I'm not familiar with `js_interop` but if it's the now preferred solution, i guess you should go down that path.

**Comment by fuzzybinary** [comment]
Okay, I'll try to look into it next week.

**Comment by fuzzybinary** [comment]
I've run some tests and it appears we can loosen the restriction to be `>=0.6.3 < 0.8.0`.  We cannot use `js_interop` yet as it appears it requires Dart 3.3 which is above our minimum supported version at the moment.

**Comment by kwent** [comment]
Loosen that restriction would be good at a first step ☺️

**Comment by fuzzybinary** [comment]
This should be fixed in 2.4.0
