### ISSUE TITLE
[datadog_tracking_http_client] Web support

### ISSUE THREAD

**Issue by egonm12** [DataDog/dd-sdk-flutter#576]
### Feature description

Are there plans to support the HTTP tracking client for the web?

**Comment by fuzzybinary** [comment]
Hi @egonm12 ,

By enabling RUM, the Datadog Browser SDK should automatically perform resource / HTTP tracking performed by XHR requests, so the tracking HTTP client shouldn't be needed.

Is there something that we're not capturing that you need us to?

**Comment by fuzzybinary** [comment]
Hi @egonm12 ,

I'm going to close this due to lack of activity.  Please feel free to respond and let me know if there's a specific feature of the Tracking HTTP Client that you're not seeing and we'll reopen.

**Comment by egonm12** [comment]
@fuzzybinary I missed your initial reply. Thanks for the response, makes sense to use the browser SDK!

**Comment by fuzzybinary** [comment]
@egonm12 The Flutter SDK on Web requires the Browser SDK to work generally, and as a side effect supports XHR tracking. But, if you see any issues with it please let me know.
