### ISSUE TITLE
Datadog RUM is not working in Flutter Web

### ISSUE THREAD

**Issue by ChanghyeonYoon** [DataDog/dd-sdk-flutter#584]
### Describe the bug

I followed the web part as written in the official documentation, but the data is not being collected in the RUM Dashboard.

### Reproduction steps

index.html
```
<script type="text/javascript" src="https://www.datadoghq-browser-agent.com/us1/v5/datadog-logs.js"></script>
<script type="text/javascript" src="https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum-slim.js"></script>
```

main.dart
```
final configuration = DatadogConfiguration(
  clientToken: datadogClientToken,
  env: Config.instance.env,
  site: DatadogSite.us1,
  nativeCrashReportEnabled: true,
  loggingConfiguration: DatadogLoggingConfiguration(),
  rumConfiguration: DatadogRumConfiguration(
    applicationId: datadogApplicationId,
    sessionSamplingRate: 100.0,
  ),
)..enableHttpTracking();

await DatadogSdk.runApp(configuration, TrackingConsent.granted, () async {
    runApp()
    }
   );
```

In Web Inspect, downloaded sdk.
<img width="738" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/71636292/4d218da6-8b1d-433c-af3f-f4a117ce345d">

But in RUM Dashboard, I can't see logs web traffic.

### Affected SDK versions

datadog_flutter_plugin: ^2.3.0
datadog_tracking_http_client: ^2.1.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Flutter Version

3.19.3

### Device Information

<img width="999" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/71636292/b08d59ae-dcc9-488b-b333-f478b15df505">

**Comment by fuzzybinary** [comment]
Hi @ChanghyeonYoon 

Did you start any RUM views in your application? Either by using the Navigation Observers or my manually calling `startView`?

**Comment by bernat-gomez** [comment]
> Hi @ChanghyeonYoon
> 
> Did you start any RUM views in your application? Either by using the Navigation Observers or my manually calling `startView`?

HI @fuzzybinary, is that step mandatory? Is there any updated docs with latest info to set up the SDK in flutter web? 

Thanks

**Comment by ChanghyeonYoon** [comment]
After add manually calling startView, it was work!
But this step in [Advanced Configutaion](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter/).
I think it need move to [mandatory step](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter)!!

**Comment by bernat-gomez** [comment]
> After add manually calling startView, it was work! But this step in [Advanced Configutaion](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/flutter/). I think it need move to [mandatory step](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter)!!

With navigators observers property at app level works as well. Thx @ChanghyeonYoon  and @fuzzybinary

**Comment by fuzzybinary** [comment]
Great you were able to get it working! I'll close this issue. If you have any other issues please let me know.

> Is that step mandatory? Is there any updated docs with latest info to set up the SDK in flutter web?

Yes, having a view active is required, so right now this step is mandatory. That said we highly recommend using the RouterObserver over manual calls to `startView` and `stopView`.

For now, Flutter Web support is fairly limited (documentation on the limitations is [here](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/flutter/#instrument-your-application)). If you need full support for Flutter Web, please reach out to your CSM to request it.
