### ISSUE TITLE
Flutter error tracking by raw code

### ISSUE THREAD

**Issue by ChanghyeonYoon** [DataDog/dd-sdk-flutter#588]
### Feature description

When I use flutter, there is no way to upload javascript sourcemaps or raw dart code.

In flutter web,
For error tracking by source code by detail, I need to upload javascript sourcemap like javascript platform RUM.

In flutter mobile(Android, iOS, ...etc)
For error tracking by source code by detail, I need to check raw dart code.

### Other relevant information

Error tracking javascript platform RUM
<img width="883" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/71636292/0a9ede15-2a49-4a7d-8299-025f971266b1">

Error tracking flutter web platform RUM
<img width="885" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/71636292/491735ba-1b9f-4616-9b1b-54614e60761c">

Error tracking flutter mobile(Android, IOS) platform RUM
<img width="894" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/71636292/45c9b5c4-efb4-4de0-b9b8-d993b3d36824">

In mobile platform (Android, IOS), there is error code line information but, doesn't show raw code like javascript platform RUM.
I want to check raw code in dashboard.

**Comment by fuzzybinary** [comment]
Hi @ChanghyeonYoon 

We do support uploading source maps for Flutter Web:
https://github.com/DataDog/datadog-ci/blob/master/src/commands/flutter-symbols/README.md

The parameter you're looking for is `--web-sourcemaps` if you're building everything to default locations.

The ability to show the raw code for Mobile RUM is a missing feature. If you could reach out to your CSM to request it as a feature tha will help us properly prioritize it.

Let me know if you have any issues getting source maps to work!

**Comment by ChanghyeonYoon** [comment]
> CSM

Where is CSM??

**Comment by fuzzybinary** [comment]
Sorry -- CSM is Datadog's abbreviation for Customer Success Manager.  It's whoever your organization's main point of contact at Datadog is. If you don't have one, let me know and I can raise the feature request for you (it's just better if it comes from your organization).

**Comment by ChanghyeonYoon** [comment]
@fuzzybinary Thx for your support.
Could you request to CSM instead me?

PS. I got involved with DASH this year by becoming a Datadog ambassador.
I'd love to see you at the event if possible!

**Comment by fuzzybinary** [comment]
Yes I'll raise it for you.

I'm not usually at DASH, unfortunately, but have fun!
