### ISSUE TITLE
FirstPartyHosts formatting

### ISSUE THREAD

**Issue by curt-weber** [DataDog/dd-sdk-flutter#603]
### Describe the bug

The `DatadogConfiguration` accepts first party hosts as a `List<String>`, but when the js script loads it complains about the format: `Datadog Browser SDK: Allowed Tracing Urls parameters should be a string, RegExp, function, or an object. Ignoring parameter`. It could be that some transformation needs to take place within the plugin to put it into a format the script expects.

### Reproduction steps

```
DatadogConfiguration(
   firstPartyHosts: ['site.com'],
)..enableHttpTracking()
```

### Affected SDK versions

2.4.0
https://www.datadoghq-browser-agent.com/us1/v5/datadog-logs.js
https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum-slim.js

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Flutter Version

3.16.9

**Comment by fuzzybinary** [comment]
Hi @curt-weber ,

Weirdly, we [do perform the transformation](https://github.com/DataDog/dd-sdk-flutter/blob/ce6cf292562ed8b61c648d6303d4eb00c723e815/packages/datadog_flutter_plugin/lib/src/rum/ddrum_web.dart#L38) to the object type the JavaScript expects.

I also can't reproduce with 2.4.0 with our simple example. 

A few questions that might help me track this down: 

Is the first party host you're setting more complex than just "site.com"? Do you know if it's working on some browsers and not others (I only tested on Chrome)?  Is there anything else weird about your setup?

**Comment by curt-weber** [comment]
No, for us it's just `kw.com`. Yes it also occurs in firefox.

**Comment by curt-weber** [comment]
Unfortunately the js is obfuscated/minified so it's harder to trace, but here it returns false:
```
function Nn(t) {
        var e = H(t);
        return "string" === e || "function" === e || t instanceof RegExp
    }
```
![firstpartyhosts](https://github.com/DataDog/dd-sdk-flutter/assets/116017986/a0d823a3-c0f6-42a2-84a3-d1092faeda45)

**Comment by curt-weber** [comment]
Actually that screenshot is from the first time it goes through that function, it goes through again but the result is the same.

**Comment by fuzzybinary** [comment]
[This](https://github.com/DataDog/browser-sdk/blob/b92c4ac8ec4d2c7a4cc2a7da5644c3cf13a84573/packages/rum-core/src/domain/configuration.ts#L155) is the code that's doing the validation. The first time it calls `isMatchOption` (the function that's obfuscated above) it should fail, but `isTracingOption` should pass in the proper `match` portion of the object.

What's `e` during the second call?

**Comment by curt-weber** [comment]
`e` is `"object"` both times - if it helps, here is a live example: [kw.com/search](https://kw.com/search/sale?viewport=30.270215809177753%2C-97.74440852131848%2C30.256723525157202%2C-97.82680598225598)

**Comment by fuzzybinary** [comment]
That does help a bit, thanks!

It's very, very strange though. We have specific code to convert the Dart `RegExp` to a JavaScript `RegExp` but in your case it looks like something might be interfering with it. Does this happen in debug builds? Is there any chance you can see what type `t` is during the call? It looks like a Dart RegExp to me, but I can't be sure.

**Comment by fuzzybinary** [comment]
I knew I saw this before -- are you sure you're using 2.4.0? The code to perform this conversion was released in 2.3.0 (see #554) and even from the obfuscated code it looks like the RegExp conversion isn't happening.  Side by side of your release code vs. mine in our sample app:
<img width="1470" alt="image" src="https://github.com/DataDog/dd-sdk-flutter/assets/249982/cb8c22e7-c5a8-4968-b898-cbb9cb43cc52">

**Comment by curt-weber** [comment]
It looks like we are on 2.2.0 - this is my fault. Apologies for the wasted cycles.

**Comment by curt-weber** [comment]
We will upgrade and confirm this works and close.

**Comment by curt-weber** [comment]
Confirmed as working - thanks for looking into this @fuzzybinary!
