### ISSUE TITLE
Support WASM for Flutter 3.22

### ISSUE THREAD

**Issue by NashIlli** [DataDog/dd-sdk-flutter#609]
### Feature description

Packages for web are updated in the new version of Flutter and they are incompatible with the current version of datadog_fltuter_pluggin when trying to compile to Wasm

**Comment by fuzzybinary** [comment]
Hi @NashIlli ,

I'll look into it ASAP. Any chance you can post what's now working or the errors you're seeing when compiling to WASM?

**Comment by NashIlli** [comment]
@fuzzybinary thans for your quick response!

Im getting the following message

```
../../../.pub-cache/hosted/pub.dev/datadog_flutter_plugin-2.5.0/lib/datadog_flutter_plugin_web.dart:12:8: 
Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html show window;
```

**Comment by fuzzybinary** [comment]
Closing and tracking as part of #615
