### ISSUE TITLE
Build error in Xcode 16 / iOS18 

### ISSUE THREAD

**Issue by ChanghyeonYoon** [DataDog/dd-sdk-flutter#627]
### Describe the bug

Ref https://github.com/DataDog/dd-sdk-ios/issues/1892

```
ios/Pods/DatadogCore/DatadogCore/Sources/Core/Upload/BackgroundTaskCoordinator.swift:29:26 Type 'UIApplication' does not conform to protocol 'UIKitAppBackgroundTaskCoordinator'
```

### Reproduction steps

Try build in Xcode16/iOS18

### Expected behavior

Upgrade new [dd-sdk-ios](https://github.com/DataDog/dd-sdk-ios)

### Affected SDK versions

2.5.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

**Comment by fuzzybinary** [comment]
Hi @ChanghyeonYoon ,

As you mentioned, this was reported in the iOS SDK as part of https://github.com/DataDog/dd-sdk-ios/issues/1892 and was fixed in their latest release.

I'm planning a Flutter release some time next week to include updated native SDKs.

**Comment by ChanghyeonYoon** [comment]
> Hi @ChanghyeonYoon ,
> 
> As you mentioned, this was reported in the iOS SDK as part of [DataDog/dd-sdk-ios#1892](https://github.com/DataDog/dd-sdk-ios/issues/1892) and was fixed in their latest release.
> 
> I'm planning a Flutter release some time next week to include updated native SDKs.

Can I try new release version now?
Because I can't build now...... :(

**Comment by fuzzybinary** [comment]
@ChanghyeonYoon 

You believe you can override the iOS SDK version in your Podfile like we do [here](https://github.com/DataDog/dd-sdk-flutter/blob/90bde211dad128486b59b6fd075ed944a766ba5e/packages/datadog_flutter_plugin/example/ios/Podfile#L36) using the most recent version.

```ruby
pod 'DatadogCore', '2.13'
pod 'DatadogLogs', '2.13'
pod 'DatadogRUM', '2.13'
pod 'DatadogInternal', '2.13'
pod 'DatadogCrashReporting', '2.13'
```

Just don't forget to remove the overrides once the new version is available.

**Comment by ChanghyeonYoon** [comment]
> ```ruby
> pod 'DatadogCore', '2.13'
> pod 'DatadogLogs', '2.13'
> pod 'DatadogRUM', '2.13'
> pod 'DatadogInternal', '2.13'
> pod 'DatadogCrashReporting', '2.13'
> ```

```
[!] CocoaPods could not find compatible versions for pod "DatadogRUM":
  In snapshot (Podfile.lock):
    DatadogRUM (= 2.11.0)

  In Podfile:
    DatadogRUM (= 2.13)

    datadog_flutter_plugin (from `.symlinks/plugins/datadog_flutter_plugin/ios`) was resolved to 0.0.1, which depends on
      DatadogRUM (= 2.11.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `DatadogRUM` inside your development pod `datadog_flutter_plugin`.
   You should run `pod update DatadogRUM` to apply changes you've made.
```

I can't override pod follow this error... :(

**Comment by ChanghyeonYoon** [comment]
It will be same error even try `update`

**Comment by fuzzybinary** [comment]
The Datadog Fluttter SDK 2.6.0 is out now and should fix this.
