### ISSUE TITLE
Web logs can't be seen in Datadog Logs

### ISSUE THREAD

**Issue by jakelowie** [DataDog/dd-sdk-flutter#656]
### Describe the bug

Hi.
I implemented Datadog logging in my flutter mobile application in staging but when it comes to web logs it seem to not work. I can't see the logs produced by my web app.

### Reproduction steps

Added this to my index.html
```
    <script type="text/javascript" src="https://www.datadoghq-browser-agent.com/us1/v5/datadog-logs.js"></script>
    <script type="text/javascript" src="https://www.datadoghq-browser-agent.com/us1/v5/datadog-rum-slim.js"></script>
```

Added this to my main.dart
```
   final configuration = DatadogConfiguration(
          clientToken: 'xxxxxx',
          env: 'staging',
          site: DatadogSite.us1,
          nativeCrashReportEnabled: true,
          loggingConfiguration: DatadogLoggingConfiguration(),
          rumConfiguration: DatadogRumConfiguration(
            applicationId: 'xxxxxxxxxx',
          ),
        );

     await DatadogSdk.runApp(configuration, TrackingConsent.granted, () async {
      runApp(
        ChangeNotifierProvider(
          create: (context) => GlobalState(),
          child: App(),
        ),
      );
```
Also added the navigatorObservers in main.dart, I am using routing

```
   @override
   Widget build(BuildContext context) {
    return MaterialApp(
      title: 'xxxxxx',
      navigatorObservers: [
        // ignore: missing_required_param
        DatadogNavigationObserver(datadogSdk: DatadogSdk.instance),
      ]
```
Added this to a class where I use log warn when a certain condition is met
```
    final logger = DatadogSdk.instance.logs?.createLogger(
     DatadogLoggerConfiguration(
      remoteLogThreshold: LogLevel.warning,
     ),
   );

      logger?.warn("Sample log...");
```
### SDK logs

There are no bugs in console log.

### Expected behavior

I expect to see the log the same as how I see the logs from mobile application

### Affected SDK versions

2.0.0

### Latest working SDK version

2.0.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Flutter Version

3.17.2

**Comment by fuzzybinary** [comment]
Hi @jakelowie ,

This should be supported, so a few things to double check:

* Do you have an ad blocker running in your browser, or some corporate policy that may be preventing Datadog from sending information from your Browser?
* How are you searching for your logs in Datadog? Have you tried going to Live Tail and filtering by your service or environment? Note that Flutter logs on web do not have `source: flutter`, they instead come back as `source: browser`.
* Do you have any log pipelines that might be messing with logs coming from `source: browser`?
* Can you try changing your `remoteLogThreshold` to something higher, like LogLevel.debug, just to see if that's causing an issue?

Lastly, I'm assuming you're using `2.0.0` as a shorthand and you're actually on the latest release of the SDK (or at least tried it from the bug report?) I seem to remember we did have a bug where logging thresholds weren't working properly early in 2.0. While I don't think that's your bug it might be worth checking.

**Comment by jakelowie** [comment]
Hi @fuzzybinary , I'm sorry I forgot to close this issue. You are right the problem was in the filter of my Datadog logs. 
So for anyone with the same problem with me let me just share with you all the filter that I used for Android, iOS, and Web

Datadog Query Web: source:browser status:warn @view.url:"https://yourdomain.com/#/"
Datadog Query Android: service:com.yourappid.sample status:warn @http.useragent_details.os.family:Android
Datadog Query iOS: service:com.yourappid.sample status:warn @http.useragent_details.os.family:iOS
