### ISSUE TITLE
Cannot set the user group

### ISSUE THREAD

**Issue by pnotel** [DataDog/dd-sdk-flutter#660]
### Feature description

Actually, we can't set the user group using this SDK (only id, name and email are available). 

It could be useful to set this property on user to be able to filter on it using facet into RUM.

**Comment by fuzzybinary** [comment]
Hi @pnotel ,

You can set custom attributes on a user using the `extraInfo` parameter of [`setUserInfo`](https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/DatadogSdk/setUserInfo.html).  You should then be able to create a facet based on that attribute.

Is that what you mean?

**Comment by pnotel** [comment]
thanks for your reply, yes I can do that, but I assume that using the default user group property (as user id, name and email) will be the best solution ? what do you think ?

**Comment by fuzzybinary** [comment]
Hey @pnotel ,

Sorry I'm confused -- are you asking for Datadog to add "User Group" as a default property available to all users, or are you seeing this in Datadog somewhere already and you're asking for the Flutter SDK to support it? I'm not aware of a "user group" currently available in Datadog.

In the first case, you can ask for that as a feature request to Datadog through our support channels or your CSM if you have one, as it's a bit more involved than just adding it to the SDK.

In the second case, can you point to somewhere in the Datadog documentation that references the feature you're referring to?

Thanks!

**Comment by pnotel** [comment]
hey @fuzzybinary 
sorry for the confusion... 
I mean the 2nd case but you are right, the documentation does not reference that... only id, name and email for user) but as you can see on the attached screenshot, the attribute seems to exist on a default facet. 
![Image](https://github.com/user-attachments/assets/b1f18f8f-607d-4593-b434-82261b3179de)

Web devs of my team are using the npm package which does not support explicit this, but allows to set 'not official' properties on user (https://www.npmjs.com/package/@datadog/browser-core?activeTab=code)

But I understand that it's complicated to support into a SDK an undocumented property ^^

**Comment by pnotel** [comment]
hi @fuzzybinary , my bad, I had not seen this parameter... yes it's exactly what I need. 
Sorry for this unnecessary issue and thanks for your time
