### ISSUE TITLE
Unable to remove unwanted Network attribute details from logs

### ISSUE THREAD

**Issue by mowi-mb** [DataDog/dd-sdk-flutter#675]
### Question

Hello,

I have installed the datadog flutter plugin and followed the setup as described. The forwarding of the logs also worked great. One thing, I came across in the logs is the extensive information with regards to the network attribute. I would like to avoid logging that kind of information. For this I found the flag `networkInfoEnabled` which I set to false when initializing my logger. Still the full network attribute was forwarded. I also tried the function `removeAttribute('network')` - without success. 
Thanks in advance for any help!

```
     final configuration = DatadogConfiguration(
        clientToken: GetIt.instance<AppConfiguration>().datadog!.clientToken,
        env: GetIt.instance<FlavorResolverService>().env.name,
        site: DatadogSite.eu1,
        nativeCrashReportEnabled: true,
        loggingConfiguration: DatadogLoggingConfiguration(),
        rumConfiguration: DatadogRumConfiguration(
          applicationId: GetIt.instance<AppConfiguration>().datadog!.applicationId,
        ),
      );

      await DatadogSdk.runApp(configuration, TrackingConsent.granted, () async {
        runApp(MyApp(initialRoute: initialRoute));
      });

  final dd_logger = DD.DatadogSdk.instance.logs?.createLogger(
    DD.DatadogLoggerConfiguration(
      service: "tbd",
      remoteLogThreshold: DD.LogLevel.debug,
      networkInfoEnabled: false,
    ),
  )
```

`datadog_flutter_plugin: ^2.8.0`
```
Doctor summary (to see all details, run
flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 15.0.1
    24A348 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices
    (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] VS Code (version 1.95.2)
[✓] Connected device (4 available)            
[✓] Network resources
```

**Comment by fuzzybinary** [comment]
Hi @mowi-mb ,

I'll take a look. Having `networkInfoEnabled` set to false should prevent the network info from being attached. There might be a bug in how its being translated.

Is this happening on both iOS and Android?

**Comment by mowi-mb** [comment]
Hi @fuzzybinary, 

thanks! Happened both on iOS and Android for me.

**Comment by fuzzybinary** [comment]
Hi @mowi-mb ,

I added an integration test in #676 that verifies that we're not sending network information when `networkInfoEnabled` is set to false. Can you double check that you're sending from a logger with that option disabled?

What network properties are you seeing? Is it possible something in your Logs Pipeline is adding them?

**Comment by mowi-mb** [comment]
Hi @fuzzybinary,

Mhh weird and thanks, already for you quick response! 
Regarding your points:

- first point: I double checked and initialized a new Logger within my `info` function that sends info logs out, so I feel rather confident that this should be a logger with this flag disabled
- second point: [Flutter_DD_network_attributes.pdf](https://github.com/user-attachments/files/17804172/Flutter_DD_network_attributes.pdf)
- third point: I am calling `dd_logger?.info(text);` directly, so I don't think so 🤔 

Will keep looking into something unusual on my side 🤔

**Comment by fuzzybinary** [comment]
Hi @mowi-mb ,

Yes, the `geoip` element is being added by Datadog's Log Pipeline as part of intake. It's not being sent by the SDK. We have a way to disable that, but I don't know it off the top of my head.  If you contact support they can walk you through how to disable geoip information.

**Comment by mowi-mb** [comment]
Thanks a ton @fuzzybinary and sorry I should have searched for removing the geoip directly!

For reference how to solve it: 
following the steps mentioned here, solved it for me: https://github.com/DataDog/browser-sdk/issues/322#issuecomment-1649447527
