### ISSUE TITLE
go_router StatefulShellRoute navigation is not detected

### ISSUE THREAD

**Issue by valerauko** [DataDog/dd-sdk-flutter#683]
### Describe the bug

It's common to use StatefulShellRoute to have multiple parallel navigation trees. Navigating between these usually happens with the StatefulNavigationShell goBranch method. This however doesn't seem to use pushNamed and is thus not detected by the Datadog SDK as navigation.

### Reproduction steps

1. define a StatefulShellRoute.indexedStack
2. use the Scaffold bottomNavigationBar to switch between branches using the goBranch method

At this point I'd expect navigation events (views) to show up in the Datadog session, but they don't.

### Expected behavior

Navigation within StatefulShellRoute branches is detected and traced according to settings

### Affected SDK versions

2.9.0

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Flutter Version

3.24.5

### Setup Type

Flutter-only app

**Comment by fuzzybinary** [comment]
Hi @valerauko ,

Is this different from the issue that we pointed out in the [documentation](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/integrated_libraries/flutter/#go_router)?

> If you are using ShellRoutes, you need to supply a separate observer to each ShellRoute, as shown below. See [this bug](https://github.com/flutter/flutter/issues/112196) for more information.

**Comment by valerauko** [comment]
Indeed it is! I did not notice that bit in the docs. Thanks!

**Comment by fuzzybinary** [comment]
No worries. I agree it should work without it but unfortunately we're limited by the library.
