### ISSUE TITLE
Understanding WebView Tracking in Datadog RUM

### ISSUE THREAD

**Issue by iwakaze81** [DataDog/dd-sdk-flutter#685]
### Question

Hi,

I would like to understand more about WebView tracking in Datadog RUM.
I am trying to monitor requests made within a WebView. For web pages that I have created and are being monitored by RUM, tracking works without any issues. However, for external web pages (e.g., https://example.com/), tracking does not seem to work properly.
What determines whether a web page can be tracked or not?

Here is the code I am using:

```dart
WebViewController()
  ..setJavaScriptMode(JavaScriptMode.unrestricted)
  ..trackDatadogEvents(DatadogSdk.instance, ['example.com']);
```

Thank you for your assistance!

**Comment by fuzzybinary** [comment]
Hi @iwakaze81 ,

WebView tracking is only meant to connect monitoring from webpages you run that are monitored by Datadog to their mobile sessions. This allows you to see the full user journey from mobile to web and back (and without being charged for those sessions separately).

It is not meant to monitor generic web traffic to / from any website you users might visit.

If you want to track which sites a user visits inside a webview that are outside of websites you control (and have user permission to do so), I would add a listener to your WebViewController and either start views manually (recognizing they won't have any events in them) or add custom actions for those web visits.

**Comment by iwakaze81** [comment]
Hi @fuzzybinary,

Thank you for the explanation. I understand.
If I need to monitor actions in an external WebView, I will use custom actions to handle this. I really appreciate your advice.
