### ISSUE TITLE
Is it necessary to call stopView?

### ISSUE THREAD

**Issue by natt-han** [DataDog/dd-sdk-flutter#688]
### Question

Hi,

Is it necessary to call stopView? Can I just use startView without stopView?

for example:
start with screen A [startView('A')] , then push screen B [startView('B')], then pop screen B back to Screen A [startView('A')]

**Comment by fuzzybinary** [comment]
No, it is not necessary to call `stopView`. Calls to `startView` stop previously active views.

It's important to know that the Datadog RUM SDKs don't actually understand "pushed" / "popped" views, and can only have one view active at a time. So in your example, when you pop Screen B back to Screen A, make sure you call `startView('A')`.
